### ISSUE TITLE
There is a mistake

### ISSUE THREAD

**Issue by TimurC1** [rms-support-letter/rms-support-letter.github.io#1175]
The user karmich (above my username) is linked twice.

**Comment by nukeop** [comment]
We will deduplicate the list once the pull requests are under control

**Comment by shenlebantongying** [comment]
Thank you for standing up and carry this mission! @nukeop

**Comment by TimurC1** [comment]
> We will deduplicate the list once the pull requests are under control

Ok, thank you! Checked update, all is fine, but my name is moved down :( but no problem :)

**Comment by imachug** [comment]
There should be no duplicates now
