### ISSUE TITLE
Add affiliation / projects. Just names is not enough.

### ISSUE THREAD

**Issue by aleksejrs** [rms-support-letter/rms-support-letter.github.io#1385]
It compares poorly to the other letter.

**Comment by GrimReaperFloof** [comment]
But are there any projects based enough to sign this?  I'd love to see it, though.

**Comment by nukeop** [comment]
I added this suggestion to the readme and the pull request template. I think it's more important to show our numbers than to win a credentials pissing contest. That can't hurt the cause though.
