### ISSUE TITLE
Wrong directory structure and field naming

### ISSUE THREAD

**Issue by cmd410** [rms-support-letter/rms-support-letter.github.io#1427]
All signatures should be in `_data/signed`, yet there are files in `_data` and `_data/signed/https:/github.com/...`

Also, field names in yaml should be all lowercase. There are some people that had written `Name:` instead of `name:` this results in empty entries in the list, because jekyll can't find `name`.

**Comment by nukeop** [comment]
I'm going to correct this manually now, thanks for noticing
