### ISSUE TITLE
I have a problems with pull request

### ISSUE THREAD

**Issue by TimurC1** [rms-support-letter/rms-support-letter.github.io#148]
#127

**Comment by ciubotaru** [comment]
Technical part aside, did you intend to sign the open letter or to do something else?

**Comment by TimurC1** [comment]
Yes

**Comment by TimurC1** [comment]
I have conflicts, in the second fork too

**Comment by TimurC1** [comment]
#165

**Comment by Jan200101** [comment]
conflicts are understandable, there is currently constant change that will add more conflicts
the people in charge of this repo are working on merging PRs and resolvingthose conflicts

**Comment by TimurC1** [comment]
Ok, thanks

**Comment by ciubotaru** [comment]
If you clearly state that you wish to sign the letter, the repo owners can do it on your behalf.

**Comment by TimurC1** [comment]
> If you clearly state that you wish to sign the letter, the repo owners can do it on your behalf.

How I can do this?

**Comment by nekonee** [comment]
Hey, I solved the conflicts, you should be on the list.

**Comment by Motophan** [comment]
Thank you brother

**Comment by TimurC1** [comment]
> Hey, I solved the conflicts, you should be on the list.

Thank you!
