### ISSUE TITLE
Please remove a fake ad website

### ISSUE THREAD

**Issue by shenlebantongying** [rms-support-letter/rms-support-letter.github.io#1527]
https://github.com/rms-support-letter/rms-support-letter.github.io/blob/master/_data/signed/chinese.yaml

He/it signed two letters, and turn out it's just an ad or spam.

![image](https://user-images.githubusercontent.com/20123683/112407465-823ae380-8cec-11eb-90de-907e7be8e0c1.png)

**Comment by 6r1d** [comment]
And I was surprised these developers signed both. Lol.

**Comment by Motophan** [comment]
the first I thought okay maybe these people just linked their project but then I realized that all their code was licensed under the Apache license

**Comment by imachug** [comment]
D'oh! Sorry for that! Removed.
