### ISSUE TITLE
Sort the list?

### ISSUE THREAD

**Issue by mhsabbagh** [rms-support-letter/rms-support-letter.github.io#1578]
The list of names is unsorted, so it makes it look a little bit unprofessional. I like sorting it by names as well so that we make sure there are no duplicates.

Can someone take the effort to write a script to sort the list automatically alphabetically?

**Comment by cmd410** [comment]
It is sorted, not by names,  but by filenames though...

**Comment by shenlebantongying** [comment]
<https://stackoverflow.com/questions/28058524/jeykll-sorting-files-in-data-subfolders-by-common-property>

This solution seems pretty reasonable, maybe we can write a simple bash or python script to do this?

![image](https://user-images.githubusercontent.com/20123683/112424347-9ee61400-8d0a-11eb-994e-79540c8d8e06.png)

**Comment by cmd410** [comment]
> <https://stackoverflow.com/questions/28058524/jeykll-sorting-files-in-data-subfolders-by-common-property>
> 
> This solution seems pretty reasonable, maybe we can write a simple python or  bash script to do this?

I think there is no need for that. Jekyll has inbuilt sorting by fields. I'll try it and tell how it goes

**Comment by shenlebantongying** [comment]
I think the liquid used by Jekyll can only do that within 1 file. That's because you cannot construct a new list/array then sort like a normal programming language...

**Comment by cmd410** [comment]
Yep, unfortunately jekyll sort doesn't work like that...

**Comment by cmd410** [comment]
Well, I managed to pull this off in liquid using captures. Thanks to this [topic on stackoverflow](https://stackoverflow.com/questions/8991995/using-liquid-to-sort-posts-alphabetically/27454206).
```
<ol>
    {% capture signs %}
      {% for sign_hash in site.data.signed %}
        {% assign signature = sign_hash[1] %}
        |{{signature.name | escape}}#{{signature.link | escape}}
      {% endfor %}
    {% endcapture %}

    {% assign sorted_signs = signs | split: '|' | sort %}

    {% for signature in sorted_signs %}
      {% assign sign_items = signature | split: '#' %}    
      <li><a href="{{ sign_items[1]}}">
        {{ sign_items[0]}}
      </a></li>
    {% endfor %}
</ol>
```
Code became somewhat uglier, but gets the job done.
The problem is... with such sorting names that start with numbers go to the top, and we all know real names don't start with numbers, so we lose some credibility like that, I think

**Comment by shenlebantongying** [comment]
There are less than 10 numeric names. Maybe we can manually tell them to change to a more formal name.

**Comment by imachug** [comment]
@cmd410 Great, can you make a PR?
