### ISSUE TITLE
issue in support of Stallman

### ISSUE THREAD

**Issue by xnngee** [rms-support-letter/rms-support-letter.github.io#1595]

**Comment by imachug** [comment]
I'd recommend you to create a PR too -- this would be more visible and your name would appear on the site.

**Comment by m-ar-c** [comment]
@xnngee you can add your signature here too (just leave a comment) : https://github.com/rms-support-letter/rms-support-letter.github.io/issues/837

**Comment by jobbautista9** [comment]
@xnngee Hey, you might've forgot to create a pull request. I see you've signed the letter in your fork.
