### ISSUE TITLE
for Appendix? open letter to the movement

### ISSUE THREAD

**Issue by jaromil** [rms-support-letter/rms-support-letter.github.io#1637]
I'll leave it here since it may be of interest:

https://medium.com/think-do-tank/open-letter-to-the-free-software-movement-7ddc7429b474

our letter here was posted in solidarity with RMS and addressed to anyone who is part of the free software movement, to make sure our principles are clear. My fear is that someone is taking advantage of this personalizing fuzz to lose the focus on principles.

**Comment by PHPoenX** [comment]
#1338

**Comment by shenlebantongying** [comment]
I think this fixed by https://stallmansupport.org

![image](https://user-images.githubusercontent.com/20123683/114263380-1f676e80-99b3-11eb-84b6-dddbb4ecf5dc.png)
