### ISSUE TITLE
Creative Graphics designer needed for Social media preview image

### ISSUE THREAD

**Issue by gorshunovr** [rms-support-letter/rms-support-letter.github.io#1732]
Creative Social media preview image design is needed for this support letter.
The image should be at least 640×320px (1280×640px for best display).
[Download template](https://drive.google.com/file/d/1A-2-ka-nOtsd9MFu5_mzZ-PbzMIz5E_T/view?usp=sharing).

Once done, image needs to be placed into `./assets` subdirectory.

**Comment by zezic** [comment]
Some attempts
![rms-design-dark](https://user-images.githubusercontent.com/1945127/112496278-a999bb00-8d95-11eb-9278-990c77c897e6.png)
![rms-design-green](https://user-images.githubusercontent.com/1945127/112496291-ad2d4200-8d95-11eb-8547-c8369c750c3e.png)
[rms-design-source.zip](https://github.com/rms-support-letter/rms-support-letter.github.io/files/6205777/rms-design-source.zip)

Let me know if any logos (GNU? FSF? GitHub?) should be added or if the photo should be replaced with some other.

**Comment by zezic** [comment]
Changed top line to fancy font
![rms-design-dark-v2](https://user-images.githubusercontent.com/1945127/112498427-91c33680-8d97-11eb-815d-9a3e2a51210b.png)
![rms-design-green-v2](https://user-images.githubusercontent.com/1945127/112498448-97208100-8d97-11eb-9dd6-07798bdea832.png)
[rms-design-source-v2.zip](https://github.com/rms-support-letter/rms-support-letter.github.io/files/6205876/rms-design-source-v2.zip)

**Comment by FreaxMATE** [comment]
This looks amazing! There is already a [PR](https://github.com/rms-support-letter/rms-support-letter.github.io/pull/1817) open, maybe you can post it there as well.

**Comment by nukeop** [comment]
This is exactly what we need.

**Comment by imachug** [comment]
Merged, thanks!
