### ISSUE TITLE
continuation: rms-open-letter denial of discussion

### ISSUE THREAD

**Issue by Jan200101** [rms-support-letter/rms-support-letter.github.io#175]
continuation of https://github.com/rms-open-letter/rms-open-letter.github.io/issues/848 (issue has since been deleted) in a place where discussion is allowed
since the people behind that repository have shown they are unwilling to have one like an adult

Here is a list of locked issues
Issue | deleted | reason | notes | archive
------- | --------- | ---------- | ------- | -----------
https://github.com/rms-open-letter/rms-open-letter.github.io/issues/120 | no | too heated | responded after followup locking | https://archive.is/1lJKy
https://github.com/rms-open-letter/rms-open-letter.github.io/issues/401 | no | no reason | [2] | https://archive.is/990bb
https://github.com/rms-open-letter/rms-open-letter.github.io/issues/667 | yes | no reason | [1] linked
https://github.com/rms-open-letter/rms-open-letter.github.io/issues/672 | yes | no reason
https://github.com/rms-open-letter/rms-open-letter.github.io/issues/676 | yes | no reason | |  https://web.archive.org/web/20210324100146/https://github.com/rms-open-letter/rms-open-letter.github.io/issues/676
https://github.com/rms-open-letter/rms-open-letter.github.io/issues/696 | yes | no reason
https://github.com/rms-open-letter/rms-open-letter.github.io/issues/756 | yes | no reason
https://github.com/rms-open-letter/rms-open-letter.github.io/issues/794 | yes | no reason | [1] linked | https://archive.is/CM9C1
https://github.com/rms-open-letter/rms-open-letter.github.io/issues/811 | yes | too heated | [1] linked
https://github.com/rms-open-letter/rms-open-letter.github.io/issues/848 | yes | no reason | `I have no interest in discussing this further here.` - neilmcgovern
https://github.com/rms-open-letter/rms-open-letter.github.io/issues/909 | no | off topic | | https://archive.is/jnH0H
https://github.com/rms-open-letter/rms-open-letter.github.io/issues/924 | yes | spam
https://github.com/rms-open-letter/rms-open-letter.github.io/issues/939 | no | off topic | asking about a gitlab repository | https://archive.is/tOj7D
https://github.com/rms-open-letter/rms-open-letter.github.io/issues/940 | yes | no reason | asked where to support RMS | https://archive.is/A0yFZ
https://github.com/rms-open-letter/rms-open-letter.github.io/issues/949 | yes | too heated | | https://archive.is/i0lSW
https://github.com/rms-open-letter/rms-open-letter.github.io/issues/951 | yes | | | [screenshot](https://github.com/M-i-k-o-t-o/rms-open-letter-removed-issues/blob/main/Screenshot_2021-03-24%20Improve%20the%20appendix%20%C2%B7%20Issue%20%23951%20%C2%B7%20rms-open-letter%20rms-open-letter%20github%20io(3).png)
https://github.com/rms-open-letter/rms-open-letter.github.io/issues/970 | yes | no reason | | https://archive.is/pgjW6
https://github.com/rms-open-letter/rms-open-letter.github.io/issues/1033 | no | off topic | | https://archive.is/yhHeL
https://github.com/rms-open-letter/rms-open-letter.github.io/issues/1136 | no | off topic | | https://archive.is/NbGsP
https://github.com/rms-open-letter/rms-open-letter.github.io/issues/1284 | no | off topic | | https://archive.is/nE4n0
https://github.com/rms-open-letter/rms-open-letter.github.io/issues/1401 | no | resolved | https://twitter.com/torproject/status/1374754834050654212 | https://archive.is/JqtOW
https://github.com/rms-open-letter/rms-open-letter.github.io/issues/2085 | no | resolved | | https://archive.is/4LTso
https://github.com/rms-open-letter/rms-open-letter.github.io/issues/2250 | yes | | | https://web.archive.org/web/20210326075456/https://github.com/rms-open-letter/rms-open-letter.github.io/issues/2250
https://github.com/rms-open-letter/rms-open-letter.github.io/issues/2259 | yes | | | https://web.archive.org/web/20210326080553/https://github.com/rms-open-letter/rms-open-letter.github.io/issues/2259
https://github.com/rms-open-letter/rms-open-letter.github.io#2414 | yes | | | https://archive.is/3nPXN
https://github.com/rms-open-letter/rms-open-letter.github.io#2427 | yes | | | https://archive.is/qT4SF

[1] https://xkcd.com/1357/

[2]
some improvements https://github.com/rms-open-letter/rms-open-letter.github.io/issues/401 ([archive](https://archive.is/990bb)), https://github.com/rms-open-letter/rms-open-letter.github.io/pull/791 ([archive](https://archive.is/DXYDj)) & https://github.com/rms-open-letter/rms-open-letter.github.io/pull/910 ([archive](https://archive.is/teDr1)) have been opened to correct the letter and have been rejected with the reasoning that the letter has been signed by too many people that altering would invalidate the the signatures

Here is a list of people in charge of the open letter repository
- @mollydb
- @neilmcgovern 
- @ehashman

This list does not exist to encourage harrasment, and I beg you not to go after these people, but rather mirrors my belives from [this issue](https://github.com/rms-open-letter/rms-open-letter.github.io/issues/383#issuecomment-805602388) ([archive](https://archive.is/SQcoh) last comment) which I am going to paraphrase again in the case it gets deleted:

- While I believe the opinion of everyone matters I also believe that on certain subjects the opinion of people outside of the subject is inherently of less value

It is best to make your own judgement on the letter and this just stands to document what has happened
In no way am I saying that closing, locking or deleting is a bad thing but the people above have not only proven to be that they are unwilling to have a discussion debating points of the letter but are also willingly malicious by citing points that are no longer true or outright lies and being unwilling to append a correction

**Comment by appetrosyan** [comment]
To be fair, we kinda have that too #24

**Comment by imachug** [comment]
That's different from locking issues though.

**Comment by Jan200101** [comment]
#24 has been closed but still allows people to comment on it

**Comment by dvz0** [comment]
https://github.com/rms-open-letter/rms-open-letter.github.io/issues/924 - also closed and locked without any reason.

**Comment by Motophan** [comment]
I support discussion. Not sure why is labeled a transphobe tbh. I get he said some bad things to someone who is trans, but he said those things to the person not the gender. It really had nothing to do with what gender they thought they were.

**Comment by josephbburg** [comment]
> I support discussion. Not sure why is labeled a transphobe tbh. I get he said some bad things to someone who is trans, but he said those things to the person not the gender. It really had nothing to do with what gender they thought they were.

It wasn't anything he said or did to any specific person. It's his position on "they/them" pronouns, which he rejects for grammatical reasons and proposes a singular alternative. Those creeps even have the audacity to call him ablest, can you believe that?

**Comment by pizdjuk** [comment]
If somebody feels that he is impacted by RMS, he could freely fork the GPL, dont use GPL software, etc. But not to offend RMS. Because there are plenty of people out there, who disagree with this mob. RMS is a rigorous leader of FSF. And his private opinion about whatever doesnt matter, since it doesnt impact the FSF movement.

**Comment by appetrosyan** [comment]
They have a point, in that RMS does not behave as a leader of a serious organisation should. The are right in that RMS can become a liability. However, politicising, boycotting, and using your leverage to oust one person because you disagree with their views is ... not a good precedent. He has the right to make amends at least. 

What I find baffling is the complete and utter lack of dialogue, and the unfair assumption that if you find his ideas problematic, that you would have no problem with using all possible leverage to get rid of him. Actions speak louder than words. He has made people uncomfortable, yes. He has spoken out against fair accusations, also yes. He has founded the movement that gave most of those people a job. The G in GTK is the same G as in GIMP, which is the same as in GNU. All of those G's are a direct consequence of his æsthetic choices. The projects that these people are maintaining are possible only thanks to his contributions. 

I don't say that this means that everyone should be kissing RMS's feet, but at least some consideration should be given to the Titanic amount of work that this person has contributed. The tone should be different. In particular I find it offensive, that the issue raising the problem of targeting him specifically , and not his misbehaviour is deleted, and all such issues are closed, because it's inconcenient to adjust the phrasing after so many people have signed. The "We don't want people like RMS" is still in their letter. 

The problem is the methods. This idiotic, blind and deaf politically-charged protest should stop.

**Comment by evrial** [comment]
Classic leftist fascist tribalism. Good for us those do a great job of collecting their names, some of them i expected to be smarter but well, thats life lets be realistic.

**Comment by imachug** [comment]
> They have a point, in that RMS does not behave as a leader of a serious organisation should.

And let's face it, this is what makes free software movement humane.

**Comment by Jan200101** [comment]
> They have a point, in that RMS does not behave as a leader of a serious organisation should.

RMS exibits a lot of weird behavior from eating his toe cheese up to dancing weirdly with a man in a gnu costume, a lot of which I would attribute to his autism
But there is a reason why RMS was the head of the FSF and created the GNU project
the man essentialy gave birth to the movement and has stuck to the morals as best as he could ever since
Sure the man does not do as much as he used to but I believe it is important to keep him around just to make sure people don't do stupid things but it seems they are trying to do him like Eric Raymond who shot down the bastardization of the original goals he had when creating the OSI and honest to god this will also come to Linus Torvalds and when it does we are in a world of trouble.
Linus has already been bending heavily to people against him, which is not entirely a bad point he has many flaws just as anyone else and tries to work on himself but that ends with him listening to people that seek to get rid of him, once Linus is completely gone who is going to make sure no one does stupid things or bastardizes what Linux is?

**Comment by appetrosyan** [comment]
Some of these issues are now deleted. I.e. I can't even read what was on there. This is part of a concerted effort to wipe any evidence of actual factual errors.

**Comment by imachug** [comment]
[censored]ing [censored]s.

![image](https://user-images.githubusercontent.com/16370781/112365103-4dc52880-8ce8-11eb-9f89-e326052ff88a.png)

**Comment by imachug** [comment]
> The Tor Project is joining calls for Richard M. Stallman to be removed from board, staff, volunteer, and other leadership positions in the FOSS community, including the Free Software Foundation and the GNU Project. Sign the open letter:

Oh. Fair. Didn't expect them to shut me up because of a single question though.

**Comment by Motophan** [comment]
Well, tor is now compromised.

Stallman being cancelled is a psyop, same reason terry davis
((((((((jumped))))))) in front of a train. They could not remove stallman
in this method because he was too big, so they killed his career.

Tor confirmed compromised.

**Comment by em92** [comment]
Adding my 2 cents.
![Снимок экрана_2021-03-25_11-57-57](https://user-images.githubusercontent.com/15870400/112431741-b8667a80-8d61-11eb-9d4c-33a90369713a.png)

"this content" link leads to my PR https://github.com/rms-open-letter/rms-open-letter.github.io/pull/791 which lead @mollydb to add similar commit https://github.com/rms-open-letter/rms-open-letter.github.io/commit/8e52fd9c1c3fbeffa6b32f8fc599aeaf5ede0571
At the moment, when @mollydb updated appendix, I was able to write on the PR. This morning in YEKT timezone, I found out that I am banned.

Also, [my suggestion](https://github.com/rms-open-letter/rms-open-letter.github.io/pull/910#issuecomment-805766674), which was marked as off-topic, became irrelevant after @mollydb updated appendix.

**Comment by shenlebantongying** [comment]
Can we pin this thread? This might have historical reference value in the future.

**Comment by CarlosGS** [comment]
This is honestly the biggest issue with the original letter. The authors are deliberately hiding (censoring) all opposing views.
People reaching that repository won't **see** any issues or anything wrong with it.

In today's busy world, few people will have time to dig deeper and question the letter and its purpose.

**Comment by CarlosGS** [comment]
I also agree this issue should be pinned, so more people can see what they are doing.

**Comment by nukeop** [comment]
> This is honestly the biggest issue with the original letter. The authors are deliberately hiding (censoring) all opposing views.

I don't find this surprising or controversial. I delete some posts from this repo too, I don't have time for this.

**Comment by Jan200101** [comment]
I wouldn't say the deletion or locking of issues is inherently a problem but rather the unwillingness to let discussion happen

**Comment by gardenBanter** [comment]
Communities of lynch mobs who censor people are full of censorship, what a shocker!

**Comment by appetrosyan** [comment]
We have laws and we have due process. RMS, being back on the board means that he signs a legally binding contract, that includes several terms on conduct. If this includes him acting like a civilised human being, and him not liking it, he is in his right not to return. If he does agree, then you can only legitimately make him step down *if* he violates said contract. He hasn’t even had a chance to do so, and there are no (as yet) laws to enforce his resignation. 

This call for his resignation  is illegitimate, because if the people who signed the petition were authorised to decide on this matter, their votes would be counted. Either they aren’t authorised, or majority thinks that RMS is fit to lead. So this is basically equivalent to a coup. You gather round and make a noise, because you didn’t win the vote. Except a lot of these people know that mob lynching and such coups are wrong, because very recently they were condemning the exact same action and calling for “voices to be amplified”. 

My problem here, is that a lot of the deleted issues are people on “their side of the fence”, trying to make the text more accurate, and more reasonable. One issue in particular, called for the letter to target the behaviour, and not the person, which would have been more in-line with the spirit of justice and clemency. 

Them deleting these issues is only making their *case* appear weaker to any reasonable person, while making it stronger (for a time) to anyone who sees the word *transphobic* sees a privileged white-old dude, and says *guilty*. This doesn’t look like an ethical organisation trying to improve its conduct, this looks like someone found some dirt on RMS, and had been eyeing his seat. This is petty.

**Comment by nukeop** [comment]
> We have laws and we have due process.

The whole point of aggressive "open letters" is to bypass laws and due process

**Comment by Jan200101** [comment]
I believe Leah Rowe, libreboot developer and someone who in the past had some beef with the FSF,  said it best
https://twitter.com/n4of7/status/1375112542595481607
> This is a coup! Hostile take over of FSF.

**Comment by M-i-k-o-t-o** [comment]
@Motophan 

> Well, tor is now compromised.

Tor as an organization was compromised at least ever since they decided to hire a cia contractor. You are ~6 years behind. https://archive.is/4FMxm

@em92
Same happened to me at issue 951, despite @neilmcgovern thanking me for being civil and @mollydb thanking me and creating a pull request to fix one of the issues that I mentioned. I woke up only to see my issue deleted and myself blocked from the project. I would not be as upset if the told me to fuck off right away, at least they would be transparent with their intentions that way. Their toxic actions made me feel betrayed.

Also, be aware that this repo is currently being suppressed by github out of the trending page.

**Comment by shenlebantongying** [comment]
@neilmcgovern and @mollydb even go to Debian's mailing list for this affair. I thought they works for GNOME now.
https://lists.debian.org/debian-vote/2021/03/threads.html#00061
![image](https://user-images.githubusercontent.com/20123683/112546273-a00d5480-8d8f-11eb-881c-79bddef625e2.png)
![image](https://user-images.githubusercontent.com/20123683/112546309-aac7e980-8d8f-11eb-92bd-35c76e53d89a.png)

**Comment by M-i-k-o-t-o** [comment]
@shenlebantongying Regarding debian: https://github.com/Enegnei/JacobAppelbaumLeavesTor/issues/21

**Comment by CarlosGS** [comment]
https://web.archive.org/web/20210326080553/https://github.com/rms-open-letter/rms-open-letter.github.io/issues/2259

**Comment by N0rbert** [comment]
The most interesting issue is 2250, it contains references to violated documents. Hope they will not remove it :)

**Comment by easymodo** [comment]
> The most interesting issue is 2250, it contains references to violated documents. Hope they will not remove it :)
 
uh huh
![image](https://user-images.githubusercontent.com/5484275/112611687-d21dc580-8e26-11eb-8a99-4b2cf952b174.png)

**Comment by imachug** [comment]
webarchive link: web.archive.org/web/20210326054602/https://github.com/rms-open-letter/rms-open-letter.github.io/issues/2250

**Comment by CarlosGS** [comment]
Internet archive doesn't let me capture this one, leaving it here in case someone can: https://github.com/rms-open-letter/rms-open-letter.github.io/issues/2285
Shared a screenshot in message above.

**Comment by imachug** [comment]
I can't save it either. Hopefully web archive is not blocking us. Oh-uh.

**Comment by shenlebantongying** [comment]
archive.is still working https://archive.is/mRPp3

We can also save a local copy by using SingleFile extension of firefox
https://addons.mozilla.org/en-US/firefox/addon/single-file/

**Comment by imachug** [comment]
*Hi, I'm a time traveler, Mozilla has banned everyone who signed rms-support-letter from using their browser*

**Comment by imachug** [comment]
Okay, can someone please make a bot to *automatically* save every new issue from that other repo? They get deleted before I can read them.

**Comment by CarlosGS** [comment]
Another one, sadly true:
![Screenshot_20210326_110318](https://user-images.githubusercontent.com/1636266/112616067-946b6d80-8e23-11eb-8948-0ad09850b258.png)

**Comment by imachug** [comment]
Sound like EEE.

**Comment by imachug** [comment]
@System0x20 Sorry for replying in this repo but it feels a bit more secure.

https://github.com/rms-open-letter/rms-open-letter.github.io/issues/2292#issuecomment-808094670

> Its name is literally README.md
> "Please note, issues about technical problems in this repository are welcome. Complaints about the content of the letter are not on topic and will be deleted - there's a lot more places that are more appropriate than opening issues."

Where would you recommend to send that warning then?

**Comment by System0x20** [comment]
> Where would you recommend to send that warning then?
@imachug as you can see the the letter is written and signed by OSI, Debian and GNOME folks (as well as a former member of the FSF board) you probably should talk about that in forums related to these foundation/organizations

**Comment by Jan200101** [comment]
> Since deleted:
> https://web.archive.org/web/20210326080553/https://github.com/rms-open-letter/rms-open-letter.github.io/issues/2259
> https://web.archive.org/web/20210326075456/https://github.com/rms-open-letter/rms-open-letter.github.io/issues/2250

Thank you for providing these

> So long for the freedom of speech.

I wouldn't call freedom of speech on this
Neil himself linked [this](https://xkcd.com/1357/) xkcd comic a few times and it is true it is their project they can do as they please (within githubs rules)
The real problem I see are
- they are unwilling to have a discussion that is even slightly critical of the letter
- willingly making false claims and refusing to alter or add a note correcting it claiming that it would invalidate the the signatures


> archive.is still working https://archive.is/mRPp3

As the issue is not locked or deleted I will not add it to the list yet but thank you for providing it

> Okay, can someone please make a bot to _automatically_ save every new issue from that other repo? They get deleted before I can read them.

as it stands both letters have slowed down and the deletion of issues isn't done too closely to its creation so manual archiving isn't too tedious
and what has already been documented is more than enough to prove that there is an inherent unwillingness to discuss 


> Another one, sadly true:
> [IMAGE]
> 
> "divide and conquer"

As I see it this is true and my concern is it that the people that created this letter are not in favor of freedom and simply seek to further their own agenda

> > Where would you recommend to send that warning then?
> 
> @imachug as you can see the the letter is written and signed by OSI, Debian and GNOME folks (as well as a former member of the FSF board) you probably should talk about that in forums related to these foundation/organizations


The letter is written and signed by a lot of groups some of which have members that actively disagree with the letter showing that that those groups support is not entirely one sided
not to mention that the OSI is not exactly a group known for their good will, a great post about the OSI is [The right to be rude](http://esr.ibiblio.org/?p=8609).

As it stands there is no open communication channel to the maintainers of that letter and github issues are disgarded on the regular.

An issue that personally bothered me is https://github.com/rms-open-letter/rms-open-letter.github.io/issues/401 since RMS has been accused of transphobia without any citation actually proving him to be (Stallman has a complicated view on the entire pronoun thing but is in favor of it. [post](https://stallman.org/articles/genderless-pronouns.html))
no modification of the letter is being made claiming
`Because many people have signed, we will not retroactively change the contents of the site.`
which is understandable but troubling
no one is asking for an inherent change of the letter, a note (as has been done on the minor topic) would be enough

To me this does not show that the people behind this letter are interested in setting right in the world but that they want to cause trouble for nothing but their own benefit.

**Comment by easymodo** [comment]
@System0x20
> go complain on random forums almost no one reads, while we are gathering an angry lynch mob on github

oh i know, how about just opening a discussions page on repo?

**Comment by System0x20** [comment]
> @System0x20
> 
> > go complain on random forums almost no one reads, while we are gathering an angry lynch mob on github
> 
> oh i know, how about just opening a discussions page on repo?

That's actually a good idea. We can (politely) ask a neutral organization (like Eclipse, they dont support anyone[yet?], Apache members support the letter) To provide both sides and not just you or those supporting the letter like me a place to talk.

**Comment by imachug** [comment]
In theory, I could create a chat from a throwaway account and delete its password. But no one will believe I did so, right?

**Comment by System0x20** [comment]
> In theory, I could create a chat from a throwaway account and delete its password. But no one will believe I did so, right?

Yep thats why I suggested to ask a neutral org. Anyone can do that but people dont believe you or me

**Comment by Jan200101** [comment]
> Yep thats why I suggested to ask a neutral org. Anyone can do that but people dont believe you or me

I doubt that is possible
Any group that seems "neutral" will have people with a bias to one side
finding a group of people that can stay neutral is hard and unverifiable
not doing any moderation will lead to trolls disrupting discussion or one side pushing out the other

**Comment by System0x20** [comment]
> > Yep thats why I suggested to ask a neutral org. Anyone can do that but people dont believe you or me
> 
> I doubt that is possible
> Any group that seems "neutral" will have people with a bias to one side
> finding a group of people that can stay neutral is hard and unverifiable
> not doing any moderation will lead to trolls disrupting discussion or one side pushing out the other

Yes but you guys are heavily biased towards the guy we are heavily biased against him. Finding somewhere just slightly biased towards or against him is the best we can do if we both don't like discussing about this in somewhere acquired by Microsoft

**Comment by appetrosyan** [comment]
I think we should wait, and see what happens. The signature collection doesn’t mean much, if the real heavy hitters pull the plug. We currently don’t have a backup, all signatures that went though the issue or the PRs may get lost if Microsoft decides to close this repo for inciting violence. The best thing that we can do, is wait, RMS is the one who can litigate, and litigation is the most reliable way to stop this. We are not at *war*, this is a disagreement about methods.

**Comment by shenlebantongying** [comment]
This would be deleted in a few minutes.

https://github.com/rms-open-letter/rms-open-letter.github.io/issues/2414

archive
https://archive.is/3nPXN
https://web.archive.org/web/20210326231941/https://github.com/rms-open-letter/rms-open-letter.github.io/issues/2414

**Comment by Jan200101** [comment]
those last two github issues were added, thanks for providing an archive.
As it stands I belive the point has been made and I simply don't want to update the list anymore

**Comment by shenlebantongying** [comment]
@Jan200101 Thank you BTW, this will leave important material for future people as reference.
