### ISSUE TITLE
Proposal: Link Git tutorials in readme?

### ISSUE THREAD

**Issue by cristeigabriel** [rms-support-letter/rms-support-letter.github.io#1769]
To make this more accessible, and to get people more prone to signing in favour of Stallman, there should be a tutorial on how to use Git linked in the README, and have this *also* be a way for people to get a small start/understandment on Git.

**Comment by cristeigabriel** [comment]
Example of project that does this: [Dress](https://github.com/komeiji-satori/Dress)

**Comment by gorshunovr** [comment]
It's entirely possible to submit PR with needed change via GitHub GUI. GUI-only tutorial would probably suffice.

**Comment by imachug** [comment]
We added an explanation of how to sign the letter using GitHub web UI, so closing.
