### ISSUE TITLE
Sharing on social media

### ISSUE THREAD

**Issue by bnainar** [rms-support-letter/rms-support-letter.github.io#1997]
Guys, pls share more in social media. We need more signatures 📝

**Comment by 6r1d** [comment]
Sure thing, [there you go](https://www.reddit.com/r/gnu/comments/mdbe09/a_support_letter_for_richard_stallman/).

**Comment by imachug** [comment]
@cmpunches Hi, I didn't know how to contact you because I'm banned from the other repo, but could you please state that **everyone** is allowed to copy your issue text? Thanks.

**Comment by cmpunches** [comment]
Everyone is allowed to copy my issue text in its entirety unmodified.

-C

**Comment by DOORAK** [comment]
> Sure thing, [there you go](https://www.reddit.com/r/gnu/comments/mdbe09/a_support_letter_for_richard_stallman/).

"**Sorry, this post has been removed by the moderators of r/gnu.**"

**Comment by franpoli** [comment]
The effensent petition against RMS and the FSF itself linked to proprietary social media. Why not do the same using free social media and show how much we really care about free software?

**Comment by 6r1d** [comment]
Please do, @franpoli

**Comment by 6r1d** [comment]
> > Sure thing, [there you go](https://www.reddit.com/r/gnu/comments/mdbe09/a_support_letter_for_richard_stallman/).
> 
> "**Sorry, this post has been removed by the moderators of r/gnu.**"

This is a very sad thing to see.

**Comment by 6r1d** [comment]
Less sad thing to see (for now) is that:
https://www.reddit.com/r/freesoftware/comments/mdjacm/an_open_letter_in_support_of_richard_m_stallman/

**Comment by 6r1d** [comment]
Time to [reupload my comment](https://open.lbry.com/@6r1d:2/support_RMS:f?r=GAaJ9s3EZNYqp61oaAXUcUzgEMPmhhf1) on Reddit somewhere.

**Comment by Renegate** [comment]
Red Hat, takes on too much: https://mobile.twitter.com/RedHat/status/1375190874011865088
