### ISSUE TITLE
Isn't it easier to just collect stars?

### ISSUE THREAD

**Issue by Zuzuk-null** [rms-support-letter/rms-support-letter.github.io#214]

**Comment by AnimusPEXUS** [comment]
How to backup stars to offline storage?

**Comment by andrew-phi** [comment]
Let's do both :)

**Comment by Jan200101** [comment]
just collecting stars is easier but its also more risky considering the removal of this repo would wipe all of those
as it stands this repo seems to be catching up to the open letter quite quickly so

**Comment by appetrosyan** [comment]
Signatures are legally binding. Stars aren't. Microsoft can choose to display the wrong number too.

**Comment by tomfun** [comment]
> Signatures are legally binding

 - what does it mean? I think to make it legally wee need to make real signs (with pen)
