### ISSUE TITLE
How come this is not in trending?

### ISSUE THREAD

**Issue by M-i-k-o-t-o** [rms-support-letter/rms-support-letter.github.io#2263]
It has more pull requests and more stars than the open letter yet it is the open letter that is in trending https://github.com/trending

**Comment by cmd410** [comment]
Legit question

**Comment by xgqt** [comment]
Come on people, we are on GitHub!

**Comment by averne** [comment]
Must be a bug, I'm sure the fine folks at Microsoft would never participate in deplatforming the biggest free software advocate.

**Comment by shenlebantongying** [comment]
If you turn off the "spoken language" filter. The freaking opposite letter will show up. We are indeed censored.

https://github.com/trending?spoken_language_code=

![image](https://user-images.githubusercontent.com/20123683/112545128-380a3e80-8d8e-11eb-9570-5e0b0dd5195d.png)

**Comment by nukeop** [comment]
Judging by the number of stars, we should be right at the top.

Trending sections on social media are notoriously manipulated though, and this might be another example.

**Comment by nukeop** [comment]
The other letter was created 1 day earlier though, and this section might only be counting repos that are at least 3 days old.

**Comment by Bluesboy** [comment]
> The other letter was created 1 day earlier though, and this section might only be counting repos that are at least 3 days old.
Let's hope so.

**Comment by Jan200101** [comment]
Github trending is weird and repositories with a lot of traction are often not shown
perhaps this is done so people can't game the system and put their repos on there?
anyway it shows up when filtering by Ruby

**Comment by Bluesboy** [comment]
Maybe we should change language to HTML as well?

**Comment by shenlebantongying** [comment]
How can we do that, throw a big useless but valid HTML file?

**Comment by shenlebantongying** [comment]
Out Ruby code come from Gemfile.lock and Gemfile.......
Maybe we just delete them since we are using GitHub's default theme without much customization. There shouldn't be any breakage in foresee future.

**Comment by cmd410** [comment]
> Out Ruby code come from Gemfile.lock and Gemfile.......
> Maybe we just delete them since we are using GitHub's default theme without much customization. There shouldn't be any breakage in foresee future.
> 
> 

I don't think it's good idea. When I first checked out that repo without gemfile it couldn't even build locally

**Comment by cmd410** [comment]
lock file can probably go though. Anyway it's regenerated from gemfile

**Comment by nukeop** [comment]
Still not trending, could someone please contact Github support about this? This is a critical moment and we definitely need to be there.

**Comment by shenlebantongying** [comment]
@nukeop we are trending actually, but only in Ruby language.....

I suspect we can trick this bar by delete Gemfile.lock or add a big valid but useless html.

So that we can be identified as HTML just like the opposite letter.

![image](https://user-images.githubusercontent.com/20123683/112603649-acbf9600-8deb-11eb-849f-f0fad782b7c4.png)

**Comment by cmd410** [comment]
I don't think language matters here. Trending page is supposed to show repos with different languages.

**Comment by shenlebantongying** [comment]
Then, someone inside GitHub maybe censored us................

**Comment by nukeop** [comment]
Maybe, but I wouldn't place blame on Github prematurely.

**Comment by fossdd** [comment]
Censoring is bad. I signed the opposite letter but both letters should be visible. Look at https://github.com/github/linguist/blob/master/docs/overrides.md if you want to "override" the language.

**Comment by AKonia** [comment]
Lol support letter has more stars, more forks, more contributors.... and still less signatures... How many fakes/bots signed for them ? Also they are censoring opinions about manipulative mood of pointing whole teams/organizations as signers without asking opinion of disinterested people - they are making a false impression like whole teams agree with them.

**Comment by Jan200101** [comment]
Looking besides the possibility of fake people and fake signatures I am more worries about people being roped in to sign any of both letters without understanding them or being willing to do research on the topic
I made the same point in the [comment that got be banned from the repo](https://github.com/rms-open-letter/rms-open-letter.github.io/issues/383#issuecomment-805666390)

**Comment by cmd410** [comment]
![Screenshot_20210326-132714_1.png](https://user-images.githubusercontent.com/48290258/112618388-1a44e400-8e37-11eb-81fc-bd88106e7c2d.png)
Wow, guys it's seem we are now a featured repository!

**Comment by nukeop** [comment]
Amazing! Great work everyone!

**Comment by averne** [comment]
> Lol support letter has more stars, more forks, more contributors.... and still less signatures... How many fakes/bots signed for them ? Also they are censoring opinions about manipulative mood of pointing whole teams/organizations as signers without asking opinion of disinterested people - they are making a false impression like whole teams agree with them.

It's probably because they allow signing by just sending an email, whereas people need to make a PR to sign this letter.
It might not seem like much for experienced developers, but many people are confused by all these source control concepts (fork, commit, PR, ...), so we alienate a lot of potential signees by having a much higher entry barrier.

On another note it's great to see this repo being featured at last!
