### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by Motophan** [rms-support-letter/rms-support-letter.github.io#2266]
I spoke with @nukeop and would just like the readme.md to reflect our conversation.

I asked where the money would go and nukeop said something to the effect of "it would be donated to the FSF or another free software group RMS supports depending on their [the FSF] decision." 

It would be nice if the Readme said something to this effect to let others know who may want to donate. 

I also suggest adding cryptocurrencies as a donation option but only those who have their ENTIRE codebase licensed in the GPL (any version). I think this is what he would have wanted.

**Comment by Motophan** [comment]
`Depending on FSF's decision, I will donate it to FSF or to another free software group` was his exact quote.

**Comment by shenlebantongying** [comment]
We can just donate to FSF, its simple https://my.fsf.org/join

I don't think we need money now, since the GitHub is basically "free"
If you want to thank nukeop himself or other helpful ppl, just click the sponsor on their profile.

**Comment by nukeop** [comment]
I was asked on matrix about supporting the project financially, so I put up a sponsorship button.

**Comment by nukeop** [comment]
After some consideration, maybe it's better for people to donate directly to FSF instead. I will write that in the sponsorship section. I'll donate what I got so far, but otherwise just treat this as some coffee money for me if you feel appreciative.

**Comment by shenlebantongying** [comment]
@nukeop its feels good that someone like you would stand up. We might all be part of a bigger history.

**Comment by mgorny** [comment]
Reading the new content of sponsors page, it sounds like the donations won't go to FSF after all. I would suggest removing the sponsor button here altogether because it makes the whole thing look like a scam to get money out of RMS's supporters.
