### ISSUE TITLE
RMS is an anti-freedom hypocrite. Let him rot

### ISSUE THREAD

**Issue by BurnyBoi** [rms-support-letter/rms-support-letter.github.io#24]
RMS doesn't give a damn about freedom. Look at how he worded Texas' decision to return to the basic constitutinoal freedoms:

![image](https://user-images.githubusercontent.com/41203525/112236206-5baa7900-8c16-11eb-8e73-abbdeceae23b.png)

He's completely in favor of unconstitutional lockdowns and mask mandates while claiming to be a freedom activist. We don't need him to promote free software any more.

**Comment by nukeop** [comment]
I know this is bait. But just to be clear, consistently with what I wrote in the letter and others signed, I can disagree with people on certain topics, while supporting them in other matters. And Stallman's opinions on a hundred different topics do not influence his ability to promote free software.

**Comment by BurnyBoi** [comment]
Cope

**Comment by nukeop** [comment]
Have sex

**Comment by BurnyBoi** [comment]
Dilate

**Comment by gardenBanter** [comment]
that's irrelevant to the free software stuff good sir, there's no chance in hell that we'd ever get a more stubborn leader of free software than good old RMS

**Comment by BurnyBoi** [comment]
Rent-Free

**Comment by appetrosyan** [comment]
I propose re-opening this issue, to hear from the people who have a detraction. Unlike the anti-RMS open Letter, we should show the willingness to hear the opposing arguments.

**Comment by Motophan** [comment]
I propose reopening this. Hear me out. So the other repo is closing anything that is any semblance of discussion or suggestion that maybe stallman is not satan incarnate. Let's not. We are better than them and can support discussion.

**Comment by 1vanK** [comment]
It is tolerance for the minority that has led to such a situation that the minority dictates conditions to the majority.

**Comment by 1vanK** [comment]
I propose not opening this. The current situation with cancel and sjw has arisen because the majority serves to the aggressive minority
