### ISSUE TITLE
Cannot make a pull request

### ISSUE THREAD

**Issue by pizdjuk** [rms-support-letter/rms-support-letter.github.io#266]
How to make a pull request to sign the petition?

**Comment by milanandreew** [comment]
You need to fork the repo first, see https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by pizdjuk** [comment]
Wow. Thx.

I only wonder, how many peoples would sign, and will not be capable of this. Its pretty difficult. Could you make some E-Mail address for supporting signs?

**Comment by milanandreew** [comment]
I think most people involved in the free software community know how to use git, and I think making it easier for every random person from Twitter to sign the letter would somewhat decrease the value of it's signatures, if you get my meaning.

**Comment by imachug** [comment]
It's actually easier. Just edit index.md via GitHub UI, it'll create the PR automatically.

**Comment by ciubotaru** [comment]
You can always send a word of support to <info@fsf.org>

**Comment by nekonee** [comment]
If you need more detailed instructions then I can provide them but I think that method mentioned by @imachug is the easiest one.

**Comment by pizdjuk** [comment]
> I think most people involved in the free software community know how to use git, and I think making it easier for every random person from Twitter to sign the letter would somewhat decrease the value of it's signatures, if you get my meaning.

No, there are many-many of such people that aren't programmers.

**Comment by pizdjuk** [comment]
> It's actually easier. Just edit index.md via GitHub UI, it'll create the PR automatically.

I tried. Seems not to work...

**Comment by pizdjuk** [comment]
Ach. Now it worked. Tnx!
