### ISSUE TITLE
language question: "removing RMS will hurt" sounds like the FSF plans to do that.

### ISSUE THREAD

**Issue by GitMensch** [rms-support-letter/rms-support-letter.github.io#2833]
As a non-native speaker I see an issue with the following part of index.md:

> ... removing RMS will hurt ...

Can someone explain to me why it says so instead of

> removing RMS would hurt

?

As far as I'm aware no one at FSF has a plan to remove RMS.
Is "removing ... would" a language construct that is more or less open for misunderstandings on the FSF's stand than the current version?

**Comment by shenlebantongying** [comment]
> As far as I'm aware no one at FSF has a plan to remove RMS.

It's not FSF are going to remove RMS.

It's the outside organizations like GNOME and others are pressuring FSF to remove RMS.

**Comment by GitMensch** [comment]
That's the same thing that I have seen so far, which is the reason for my question / suggested change:

```diff
-Removing RMS will hurt FSF's image and will deal 
+Removing RMS would hurt FSF's image and will deal 
```

**Comment by nukeop** [comment]
This is semantically correct as it is now.

**Comment by GitMensch** [comment]
Do you mind to explain the difference between the semantics (this _may_ also help with the correct translation)?
