### ISSUE TITLE
A mirror, because why not.

### ISSUE THREAD

**Issue by stnby** [rms-support-letter/rms-support-letter.github.io#2922]
https://gitlab.gnome.org/stnby/rms-support-letter-github-io

**Comment by shenlebantongying** [comment]
Hahaha, that's trolling.

The open letter was originally GNOME foundation's Molly de Blanc and possibly Neil McGovern. They will ban you soon.

https://github.com/rms-open-letter/rms-open-letter.github.io/commit/caa1b90876d46980cd45c04bdfae419059294e22

**Comment by stnby** [comment]
> Hahaha, that's trolling.
> 
> The open letter was originally GNOME foundation's Molly de Blanc and possibly Neil McGovern. They will ban you soon.
> 
> [rms-open-letter/rms-open-letter.github.io@caa1b90](https://github.com/rms-open-letter/rms-open-letter.github.io/commit/caa1b90876d46980cd45c04bdfae419059294e22)

Yeah I do know they will ban me. But GNOME doesn't make any quality software anyway.

**Comment by appetrosyan** [comment]
Maybe we should ask for a refresh in their leadership too? Fire these political mouthpieces and hire people that care about the UX and the UI.

**Comment by shenlebantongying** [comment]
@appetrosyan I don't think that's possible. GNOME is somehow RedHat's product now since it is developed 85%+ by RedHat  https://blog.gtk.org/2020/12/17/who-wrote-gtk4/

**Comment by isu29** [comment]
> By their logic, we should ask for a refresh in their leadership too. Fire these political mouthpieces and hire people that care about the UX and the UI. I’m sure there’s plenty of dirt on the head of Gnome foundation.

lets make an open letter to seize the means of production of GNOME and RED HAT

**Comment by Shamar** [comment]
> lets make an open letter to seize the means of production of GNOME and RED HAT

More seriously, it would be interesting to see the overlaps between the signers of both letters and a pichai-open-letter, asking to Pichai and Google's Board of Directors to resign for surveillance capitalism, tax "optimizations", ICE, military contracts, anti-union practices, ambiguos management on harrasment cases and so on.

I would happily sign such kind of letter (assuming it doesnt insult Pichai personally, calling him "misogynist, ableist, and transphobic" or the like).

And we could likewise write a bezos-open-letter and so on, for every CEO of GAFAM, but always polite and nice, but clear, firm and well documented.

**Comment by jobbautista9** [comment]
@stnby Your mirror is behind by 4 days, you might want to update it. :)
