### ISSUE TITLE
Can't sign, Help !

### ISSUE THREAD

**Issue by ObscureXwing** [rms-support-letter/rms-support-letter.github.io#2929]
Hi guys, I'm sorry to bother you, but for some reason I can't sign, I don't know why, I already tried to change the file name by removing the ".yaml" extension, tried to remove the lines and leave only name and link, and still I'm getting an error, I don't know what's the matter, but I really want to support Stallman! Please help me to solve the issue

https://github.com/rms-support-letter/rms-support-letter.github.io/pull/2903
![Снимок экрана в 2021-03-26 22-38-33](https://user-images.githubusercontent.com/66114622/112656227-dc0cec00-8e59-11eb-8e09-875e3d1cc5a9.png)

**Comment by shenlebantongying** [comment]
If you want to include your YouTube channel, you can

`simonbright.yaml`
```
name: Simon Bright (Short description)
link: https://www.youtube.com/channel/UCnQfpqJI9wjcqW-4JS8k-Rg/
```

**Comment by ObscureXwing** [comment]
> The checker doesn't matter.
> 
> If you want to include your YouTube channel, you can
> 
> `simonbright.yaml`
> 
> ```
> name: Simon Bright (Short description)
> link: https://www.youtube.com/channel/UCnQfpqJI9wjcqW-4JS8k-Rg/
> ```

Thank you !

**Comment by imachug** [comment]
Closing because you were added.
