### ISSUE TITLE
Add Japanese Translation

### ISSUE THREAD

**Issue by K-REBO** [rms-support-letter/rms-support-letter.github.io#2992]
Hi. I'll translate README and WebSite. And I report it for refer on commit.

**Comment by shenlebantongying** [comment]
That's great! Thank you

**Comment by shenlebantongying** [comment]
Someone else is working on it. 
https://github.com/rms-support-letter/rms-support-letter.github.io/pull/2970/files

**Comment by K-REBO** [comment]
Thanks!. and I'll work together

**Comment by K-REBO** [comment]
He did work in https://github.com/rms-support-letter/rms-support-letter.github.io/pull/2970/files .
close this.
