### ISSUE TITLE
How to sign via PR without having to create a fork in own profile?

### ISSUE THREAD

**Issue by fuckyourselfup** [rms-support-letter/rms-support-letter.github.io#3102]
Read title.

**Comment by cmd410** [comment]
There is no way to create pr without a fork.

**Comment by cmd410** [comment]
But you can always delete it afterwards

**Comment by shenlebantongying** [comment]
Use email or comment instead?

https://github.com/rms-support-letter/rms-support-letter.github.io/issues/837

**Comment by imachug** [comment]
Closing because the discussion seems to be over, please reopen if I'm mistaken.
