### ISSUE TITLE
Move entries with real names to the top.

### ISSUE THREAD

**Issue by OdinPreston** [rms-support-letter/rms-support-letter.github.io#311]
I think that signatures that are real names, instead of just Github nicknames should be moved to the top. I can see why some people would not use their real life credentials when signing, and you shouldn't force them to, but it would probably make a better impression if people who open the letter immediately see that real people have signed it (and it could set an example to make people more willing to use their real name when signing).
![letter](https://user-images.githubusercontent.com/80542853/112305024-1af24480-8c96-11eb-94bb-01b8414c058f.png)

**Comment by nukeop** [comment]
Good idea, we'll consider this along with displaying names alphabetically.

**Comment by jobbautista9** [comment]
To me, it could be the opposite; the current listing of signatures makes it look more legitimate and grassroots, than the other open letter which looks corporate-looking.

Maybe add it as an option instead.

**Comment by cmd410** [comment]
The problem is, how do we distinguish a real name from an alias. There are like 2.5k people now, going through all of them manually will take ages, I think

**Comment by OdinPreston** [comment]
> The problem is, how do we distinguish a real name from an alias. There are like 2.5k people now, going through all of them manually will take ages, I think
If you are talking about just determining whether a name is valid, I came up with this when making food:
1. A valid real person's name consists of at least 2 parts, a given name and a surname.
2. Person's real name can consist of more than 1 given names.
Thus, the algorithm could be something along the lines of
1. Get list of entries.
2. Check if it has at least 2 non-parenthesized, non-quoted words.
3. Check if the first word is a given name.
4. If it isn't, then check if the last word is.
5. If checks 2 and either 3 or 4 succeeded, put the entry in proper name list.
6. If the checks 3-4 failed, put the entry into possibly proper name list.
7. Otherwise put the entry into not-proper name list.
Then just print them in the order you'd like. To account for multiple given names, you might want to run checks on in-between words, if 3 and 4 failed, if you're so inclined.
I have created a script to do all of this. There are issues though. First of all, it uses wiktionary to test if names are valid; thus name that is not standard spelling or not in their database will be seen as possibly proper name. Second, because it needs to query wiktionary for every valid word (and since timeout is in good taste), it runs pretty slow - to parse all of the entries (I think 2713 at the time of writing), it took 33 minutes and 18 seconds. I think it could be used to sort entries already present, and checks could be made on newly-added ones. I have included the script, as well as its output (full output, only names, output by category of name: proper, possible, improper). It's up to you whether the results are satisfactory enough to use it.
If you are talking about determining whether a real person is behind a proper name, I'd say it's impossible, unless you require the signees to include concrete proof of their identity.
Man, github doesn't support .sh files apparently, so here's everything just dumped to a github gist instead.
The script: https://gist.github.com/OdinPreston/d10577bbf59040f9f4bb3f52ee848fe4
The output: https://gist.github.com/OdinPreston/e79efa3b4519aeb66e24ae2085f9fe71
Raw output: https://gist.github.com/OdinPreston/a9742a3e2652fb37a67f80c79f3ba6ea
Proper names: https://gist.github.com/OdinPreston/97d4d6418866fc607ecb01579c3c4ea0
Possibly proper names: https://gist.github.com/OdinPreston/9ab8a82be6e08dc6d6eafa1c88d2df27
Improper names: https://gist.github.com/OdinPreston/3f8ad157e7fb22f04d32a02c49f375e2

**Comment by stuardreinhild** [comment]
Why you suggest discriminating againt unreal names ??

**Comment by 6r1d** [comment]
It's not discriminating, but (sadly) it's about confirming we're real people with our projects as much as we can, see the first comment's picture, a response from Richard Stallman.
