### ISSUE TITLE
question: who owns github? what is their history?

### ISSUE THREAD

**Issue by jnorthrup** [rms-support-letter/rms-support-letter.github.io#3113]
the feasability of doing this, here, and self naming an inventory of those opposed to dismantling RMS needs to be managed in the context of github's corporate ownership hierarchy.

**Comment by isu29** [comment]
Microsoft owns Github
Microsoft came up with the term "open source" to shadow and diverge from the original Free Software (Libre) in the 90s too.
I bet its pure coincidence everything that's happening right now.

**Comment by shenlebantongying** [comment]
We are actually all normal people, we don't have a strict "organizational" bullshits. No one ask anyone to do something. We all volunteered to do it. Just like the original free software itself.

As for GitHub's problem, that's the result of rms-open-letter. As a counter letter, we just have to choose the same technical thing for quick response.

**Comment by jnorthrup** [comment]
does RMS's 2019 headline coincide in any way with Microsoft's acquisition of github? and, curious here, is microsoft paying taxes in Ireland instead of Redmond?

**Comment by nukeop** [comment]
I think Github has been managed very well, as far as MS acquisitions go.

**Comment by jnorthrup** [comment]
github has been running well enough but we are talking about microsoft enemy #1 getting internationally persecuted on all international media outlets at once continuously and then we find a call to self-identify any who oppose.  

perhaps gituhb ID's is an unwise choice of signatory conribution.

**Comment by shenlebantongying** [comment]
@jnorthrup We don't specifically require GitHub's ID, you can use website or other references for the link. However, not everyone has a website or other things to prove identity.

**Comment by zwonaka** [comment]
Microsoft and they are doing  great job

**Comment by jnorthrup** [comment]
@zwonaka we'll take your endorsement into consideration given that your account on this site is two hours older than this comment above.

**Comment by isu29** [comment]
> Microsoft and they are doing great job

Do microsoft support free (as in libre) software? I don't think so, they invented the idea of "open" software tho.
Really makes my noggin joggin.

**Comment by cmpunches** [comment]
When you look at who is sponsoring OSI (the org that is running the smear campaign) this is a sound recommendation.  We should at least mirror to somewhere else as a backup out of reach of their sponsors.
