### ISSUE TITLE
Signature from IRC

### ISSUE THREAD

**Issue by Tyil** [rms-support-letter/rms-support-letter.github.io#3182]
A user on Freenode's `#free-rms` wants to have their signature added, but are unable to make a signed git commit for submission on the mailing list, can't use GitHub, and doesn't want to use CodeBerg.

It is a registered nick making the request, which is over 2 years old, so reasonable to believe that this is a legitimate account from a real user. Is there any possibility this user's signature can be accepted, and if so, what information would you like to be part of the commit message, as proof that this is a legit signature?

**Comment by shenlebantongying** [comment]
Why so, if someone can connect to the internet, there are plenty of email services that he can use.

**Comment by shenlebantongying** [comment]
The best way is to sign via a GPG key, but that might be too complicated. How about some links to their social media or name on other places.

**Comment by MattMadness** [comment]
I signed for danielp3344 on freenode IRC, why not do that?

**Comment by Tyil** [comment]
Alright, sounds like this can be closed for me, I have the information I desired.
