### ISSUE TITLE
We have roughly the same number of signers as the open letter now.

### ISSUE THREAD

**Issue by shenlebantongying** [rms-support-letter/rms-support-letter.github.io#3190]
This is my personal opinion:

A lot of people was actually too afraid to talk, because they are surrounded by people hyped to destroy FSF and RMS.

Those, who works for big companies/organizations, cannot support us publicly, since they might lose the job for doing that.

We may be able to reach a **tipping point** that the supporters begin to realize that they are not the obsolete minority. If they speak, they can find friends with similar views. Even they do not support RMS or hate RMS, they can still begin to question and disagree about the unholy open letter. More people will actually read and think about the open letter and realize what they actually signed.

I already noticed that a lot of people/medias/websites begin to share this letter with questions for the whole thing in many places.

What we are doing may become a unremarkable but significant factor for the future.

**Comment by MattMadness** [comment]
We just surpassed them. I hope that we can get some of the people on the other side to change their hearts and minds and forgive Stallman and become better people, some of the people like Coraline Ada Ehmke are just really mean and hateful (She tweeted "Change or die" not too long ago, and made the proprietary Hippocratic License which she keeps lying saying that is was and oss license).

**Comment by isu29** [comment]
we did it boys, we are the leading opinion, they - by their own rules, have been defeated

**Comment by dodobyte** [comment]
> A lot of people was actually too afraid to talk, because they are surrounded by people hyped to destroy FSF and RMS.
This alone is a proof how """"liberal"""" these people are.

I personally don't even like RMS and that's irrelevant, the real issue here is greater than RMS, it's our freedom of expression on the internet. Many people are reluctant to express their ideas in fear of cancellers.

The situation progresses very fast towards dystopia. We can lose our career and get lynched out of a sentence we've written ten years ago or a remark that's misinterpreted deliberately.

I hope things get better but to be honest I'm not very optimistic.

**Comment by MattMadness** [comment]
> > A lot of people was actually too afraid to talk, because they are surrounded by people hyped to destroy FSF and RMS.
> 
> This alone is a proof how """"liberal"""" these people are.
> 
> I personally don't even like RMS and that's irrelevant, the real issue here is greater than RMS, it's our freedom of expression on the internet. Many people are reluctant to express their ideas in fear of cancellers.
> 
> The situation progresses very fast towards dystopia. We can lose our career and get lynched out of a sentence we've written ten years ago or a remark that's misinterpreted deliberately.
> 
> I hope things get better but to be honest I'm not very optimistic.

Optimism is what we need. We cannot back down from this. We must hold our ground, look at the future, and keep beating them at their own game.

**Comment by antiwoke** [comment]
Never bend the knee to the authoritarian scumbags of the religion of wokeness. They are weak, they need lies, new-speak, censorship and de-platforming. We don't. This is a great advantage. This attack on RMS and the FSF is an opportunity to reveal just how toxic, destructive and dangerous they really are.

**Comment by yw662** [comment]
Most people are not afraid to talk, they are just censored by them. Them now have only 1 open and 35 closed issues and still claim they are a part of the free software movement.
But censorship itself is effectively against the freedom 0 : people have the freedom to speak, as they have the freedom the use the software however they want.
So they are against freedom 0 indeed. They are against the movement.

**Comment by mazznoer** [comment]
They disabled the issues now.

**Comment by nukeop** [comment]
We have beaten them by several hundred signatures, I think this can be closed now.
