### ISSUE TITLE
Bots

### ISSUE THREAD

**Issue by 6r1d** [rms-support-letter/rms-support-letter.github.io#3279]
Let's be super careful about not accepting bots like [this one](https://github.com/rms-support-letter/rms-support-letter.github.io/pull/3243).

Ugh, and what to do about ingenious profile names like [this one](https://github.com/rms-support-letter/rms-support-letter.github.io/pull/3274)?

**Comment by JesseCharlie** [comment]
I am not a bot; bruh you do not want a signature? lol

**Comment by JesseCharlie** [comment]
I can remove everything in parentheses like bruh ok.

**Comment by dzhigit1** [comment]
@JesseCharlie For some reason 2 of your links were broken, and 1 redirected to the White House.

**Comment by JesseCharlie** [comment]
Ok, I'll fix them then. 1 min

**Comment by shenlebantongying** [comment]
He uses shitcum123 for internet, but actually fill a real name for `name: `.

Not everyone uses GitHub, so some of them only have rare activity on it.

**Comment by JesseCharlie** [comment]
Fixed it. Making a new pull request.

**Comment by BeyondMagic** [comment]
> Ugh, and what to do about ingenious profile names like this one?

Ingenious profile names has nothing to do with their person, this repository is being shared at some places where people don't like Github, so they probably did use their profile here just to sign in the letter or created to do so.

**Comment by 6r1d** [comment]
> I am not a bot; bruh you do not want a signature? lol
Best to check, is it not? I want all the signatures for this cause, but they should be linked to people, otherwise other letter's side will point fingers at us and tell "bots and more bots".
