### ISSUE TITLE
Update url on TTI Russian department / baterflyrity

### ISSUE THREAD

**Issue by 6r1d** [rms-support-letter/rms-support-letter.github.io#3284]
There's a broken link in [this commit](https://github.com/rms-support-letter/rms-support-letter.github.io/commit/a83c5415de8514b155f3192db9f2bad41085074e). Let's decide what to do about it.

**Comment by dzhigit1** [comment]
@baterflyrity можете исправить ссылку?

**Comment by baterflyrity** [comment]
> 
> 
> @baterflyrity можете исправить ссылку?

We dont have separate link so just leave as is.

**Comment by imachug** [comment]
`/#` is actually not a broken link but a placeholder, `check-signatures-format.py` allows it.
