### ISSUE TITLE
Request for Blank Template of /assets/social-media-preview.png

### ISSUE THREAD

**Issue by ChanoSan** [rms-support-letter/rms-support-letter.github.io#3324]
I'd like to request a blank, text-less image template of /assets/social-media-preview.png to adapt into other languages.
I attempted to overlay Japanese, and use my GIMP-fu to remove the English as cleanly as possible, but it still looks dirtier than I'd like. If I could get a blank template, it would look more professional, and it would allow other localizers to modify it as well.

**Comment by imachug** [comment]
cc @zezic

**Comment by imachug** [comment]
Here you go: https://github.com/rms-support-letter/rms-support-letter.github.io/files/6205876/rms-design-source-v2.zip

**Comment by jobbautista9** [comment]
@imachug Should we put our translations to the assets/ or _translations/?

**Comment by imachug** [comment]
`assets/social-media-preview_en_US` please (replace `en_US` with appropriate language code).

**Comment by jobbautista9** [comment]
Thanks.

**Comment by ChanoSan** [comment]
Oh, snap... should have named the image social-media-preview_ja_JP.png in my PR, then...

**Comment by jobbautista9** [comment]
I'm going to close this issue since the SVG is now available. I will be pinning this issue so that other translators can be able to translate the image as well.

**Comment by jobbautista9** [comment]
Ah shoot, you can only pin a maximum of 3 issues...

**Comment by ChanoSan** [comment]
Probably best to add the info into CONTRIBUTING.md

**Comment by jobbautista9** [comment]
Yeah, that's a good idea.

**Comment by hexherhide666** [comment]
k
