### ISSUE TITLE
Properly validate and process signatures accepted via email

### ISSUE THREAD

**Issue by KOLANICH** [rms-support-letter/rms-support-letter.github.io#3405]
1. Create a separate dir for ones.
2. All the signatures must be properly signed:
    1. Ideally OpenPGP/minisign/signify-signed with keys with proper security properties and public confirmation of the fact that a key belongs to a person:
         * being published on a well-known website of a well-known person
         * being set for a GitHub/GitLab/SourceHut/other forge account of a ["real"](https://github.com/rms-support-letter/rms-support-letter.github.io/issues/2553) person
    2. DKIM if not signed with a personal key. For DKIM in order the proof to be sound we need some trusted third party to timestamp a key that it was in use by some date for the [possible case that in future private keys may be publicly dustributed](https://blog.cryptographyengineering.com/2020/11/16/ok-google-please-publish-your-dkim-secret-keys/). I usually use WebArchive Wayback Machine as a timestamping service and DNS over HTTPS resolvers supporting returning results in JSON, such as CloudFlare and Google, as convertors dns -> JSON available over HTTP, because WA supports only HTTP. The person also should be real.
3. The email addresses should be obfuscated from spambots. Solution is to encrypt them and put a key near them.
4. It would be nice to add a script to automatically bulk-verify the signatures. Take this:

```python
import sys
import typing
from pathlib import Path, PurePath
from zipfile import ZipFile

import dkim

__license__ = "Unlicense"
__copyright__ = r"""This is free and unencumbered software released into the public domain. Anyone is free to copy, modify, publish, use, compile, sell, or distribute this software, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means.
In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain. We make this dedication for the benefit of the public at large and to the detriment of our heirs and successors. We intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
For more information, please refer to <https://unlicense.org/>""" 

def defaultPwdFun(x: Path) -> bytes:
	pass

def getArchivedDnsResponses(ns, timeout):
	import requests
	res = requests.get("https://web.archive.org/web/20201219224755if_/https://dns.google/resolve?name=" + ns + "&type=TXT&do=true&edns_client_subnet=0.0.0.0%2F0&ct=application/dns-json").json()
	k = res["Answer"][0]["data"][1:-1].encode("utf-8")
	return k


def iterEmails(dirOrArchive: Path, pwdFun: typing.Optional[typing.Callable[[PurePath], typing.Optional[bytes]]]=None) -> typing.Iterable[typing.Tuple[str, bytes]]:
	if dirOrArchive.is_file():
		if pwdFun is None:
			pwdFun = defaultPwdFun
		with ZipFile(str(dirOrArchive)) as z:
			for fi in z.filelist:
				fn = PurePath(fi.filename)
				if fn.suffix == ".eml":
					yield fn.stem, z.read(fi.filename, pwdFun(fn))
	else:
		for mfn in sorted(dirOrArchive.glob("*.eml")):
			with mfn.open("rb") as f:
				yield mfn.stem, f.read()


def main(dirOrArchive: Path, pwdFun: typing.Optional[typing.Callable[[PurePath], typing.Optional[bytes]]]=None):
	for name, msg in iterEmails(dirOrArchive, pwdFun):
		d = dkim.DKIM()
		d.add_frozen((b'date', b'subject', b'to', b'cc'))
		d.set_message(msg)
		#res = d.verify(dnsfunc= getArchivedDnsResponses)
		res = d.verify()
		print(name, "\t", d.signature_algorithm.decode("ascii"), "\t", d.keysize, "\t", (str(d.pk["publicExponent"]) if hasattr(d, "pk") else ""), "\t", d.domain.decode("ascii"), "\t", d.selector.decode(), "\t", ("\x1b[32mValid\x1b[39m" if res else "\x1b[31mInvalid\x1b[39m' "))

if __name__ == "__main__":
	pwd = None
	if len(sys.argv) > 2:
		pwd = sys.argv[2].replace('2', '3').encode("utf-8")  # cleartext password obfuscation
	main(Path(sys.argv[1]), lambda x: pwd)
```

It would be nice to improve it enough to make it a separate python package.

**Comment by Tyil** [comment]
Why do you want such strong measures for those who want to sign using free software, while there's very lax standards for the people using the proprietary (github) solution? I'd think we want to support the free software approach, given that this is all about the father of free software we're trying to support here.

Keep in mind, anyone can make spam accounts on Github right now, and add their signatures to this repository, and no-one would bat an eye. Similarly, the signatures coming from Codeberg don't seem to be held to such high standards either.

**Comment by machomanehmke** [comment]
Until you want government signed IDs and Passports, you are not secure, fellow man, you see, I have 7 burner phones, and I can make countless email addresses and generate limitless keys too. 
Nice code otherwise.

**Comment by KOLANICH** [comment]
One can create quite some emails with "burner phones", but one cannot create such amount of meaningful contributions into "real" repos. Even getting a single contribution merged is hard work. It cannot be really automated: even if a contribution is obviously useful, one has to persuade repos' owners, and often the PR is rejected on the basis "I know it is useful, but I am a BDFL and I just find it inconvenient for me". Anyway, real people in FOSS usually have enough of their contributions merged. Newly-created bots usually don't, no matter how many verified accounts they have.

>Until you want government signed IDs and Passports,

Absolutely no. Just a confirmation that there is a real person behind a "signature", not a bot. Quality is more important than quantity.

**Comment by KOLANICH** [comment]
>anyone can make spam accounts on Github right now, and add their signatures to this repository, and no-one would bat an eye. 

In #2553 where automated checks were proposed, it was claimed it is too important to not to allow to compromise the initiative, to rely on dumb software for that. So I hope the ones merging do some checks to verify that a person is a real one (BTW I saw quite some real persons I remember because of their online activity (in form of source code and articles) in the list of signatorees).

**Comment by machomanehmke** [comment]
> One can create quite some emails with "burner phones", but one cannot create such amount of meaningful contributions into "real" repos. Even getting a single contribution merged is hard work. It cannot be really automated: even if a contribution is obviously useful, one has to persuade repos' owners, and often the PR is rejected on the basis "I know it is useful, but I am a BDFL and I just find it inconvenient for me". Anyway, real people in FOSS usually have enough of their contributions merged. Newly-created bots usually don't, no matter how many verified accounts they have.

You are assuming that only developers and people who contribute to Free (Libre) Software care about it. I am not a developer myself, nor I ever contributed anything, yet I appreciate what RMS have done and everyone in that community.

**Comment by imachug** [comment]
I do not want to verify email signatures, at least at this moment. I have received only a few dozen emails yet and they all look different, come from different addresses and hosts, use different style, and provide patches in different formats. I will ask people to verify their identity if I notice something fishy, but until then I don't want to make signing too difficult.
