### ISSUE TITLE
Can I make PR of signs by proxy gathering signs from some other site's comment section?

### ISSUE THREAD

**Issue by greenhorse-effect** [rms-support-letter/rms-support-letter.github.io#3608]
I posted rms-support-letter on some forums.  A member of the forum said that signing process was too difficult.  I think non-tech savvy people seem to have trouble using Git.

So I think that if they comment their sign (name, link), then I can collect them and make a PR by proxy.  I can prove that they have signed by putting the URL of comment on the commit message.

**Comment by shenlebantongying** [comment]
They can sign via email. Do they have trouble using email?

~tyil/rms-support@lists.sr.ht
signrms@prog.cf

The frist email is public availabe at https://lists.sr.ht/~tyil/rms-support

**Comment by 6r1d** [comment]
the email should be GPG-signed, by the way: we need a proof of identity

**Comment by greenhorse-effect** [comment]
@6r1d 
> a proof of identity

Hmm, You're right.  I agree that's the crucial part.

I think PR by proxy was not a good idea.

Thanks.
