### ISSUE TITLE
So your silencing me... I repeat what I said then.

### ISSUE THREAD

**Issue by FrostKnight** [rms-support-letter/rms-support-letter.github.io#3768]
Silencing views you don't agree with is wrong.
Trying to kill the FSF over their mistakes to the degree your doing it, is also wrong.   You should not, I repeat, not try to cancel the whole board just because of Stallman. Also, he worked hard to get where he is, you are just being evil from what I see...
I am concerned your only goal is to kill software freedom in the world. Your going to have to be a bit less judgmental, otherwise people will go against you and everything you stand for.
Also, its his foundation, and his organization. You want to remove him from GNU and FSF correct? You and everyone who is doing this, seems suspect.
I may not agree with everything he does, aka, he doesn't take on all software freedom issues such as the whole init freedom thing and things like it,v but man you guys are too judgmental. 
As Lincoln said once, why do you look at the speck in your brother's eye when you have an entire plank in yours. Aka, your being a hypocrite...
If you guys keep doing this, you will kill software freedom.  And if that happens, propreitors will eventually mess things up back to the level they used to be at.
Also, people will hate you even more than they do now. You are ignoring the reason your getting push back. 
It is his organization not yours.
I am not a huge fan of GNU due to things like redhat and their damned services, gnome, dbus, pulseaudio, systemd, etc... but even that doesn't justify what you are doing.
And before you reply and think about hiding my response or w/e, just know, I am doing this because your brazen attempts to kill GNU make you seem like you want proprietary software to win.
I am skeptical that you have any other plans beyond this.
I hope I am wrong, but you really don't seem like you care at all. 
I say this because you keep hiding or silencing comments that oppose you.
That is straight up pure evil.
If you have a problem with Stallman and its still happening and he refuses to change his ways. Fine,
but even then, having all of his staff sacked with him on both GNU and FSF,  that is utterly wrong.
So yeah, I don't trust you and no one else should.

**Comment by OdinPreston** [comment]
I think you got the wrong letter buddy. The Anti-RMS letter is two blocks down: https://github.com/rms-open-letter/rms-open-letter.github.io.

**Comment by nukeop** [comment]
Who are you and why are you posting this here?

**Comment by FrostKnight** [comment]
I thought this was the other one...

**Comment by FrostKnight** [comment]
IF you want my signature btw, you can have it, but for it to be more effective, you may want to delete these threads i just made...

PS, sorry... for railing against the wrong person.

**Comment by BlueFlo0d** [comment]
> IF you want my signature btw, you can have it, but for it to be more effective, you may want to delete these threads i just made...
> 
> PS, sorry... for railing against the wrong person.

Can you submit a PR to add your signature, or follow steps for other options as in README?

**Comment by FrostKnight** [comment]
I did so just now on codeberg, under a different username.  I probably shouldn't say which username. Aka, dont add mine here...
