### ISSUE TITLE
There should be more focus on defending freedom of speech in the letter

### ISSUE THREAD

**Issue by zareami10** [rms-support-letter/rms-support-letter.github.io#3779]
To be fair, I personally don't know RMS much and I don't really care what happens to FSF, as it has been pretty much irrelevant in recent years.

But this whole incident and its implications  go far beyond RMS. They're basically cancelling someone merely because of their peacefully stated opinions, and that kind of attack on the freedom of thought and speech should not be tolerated, no matter whether we like/dislike the person in question and their opinions. There is no end to such a trend. Cancelling people merely because of disagreement will become a norm and that bar on "controversy" would be lowered day by day until almost no new opinions could be expressed.

And this is why I suggest to focus more on the presumably more important big picture too. People can agree or disagree with RMS or anyone else really, but they shouldn't be supporting a fight against freedom of speech.

**Comment by nukeop** [comment]
We're not defending freedom of speech though, that's a red herring.

**Comment by zareami10** [comment]
> We're not defending freedom of speech though, that's a red herring.

I don't know how you can separate the two issues, almost all the attacks (including the appendix on the open letter) are based on RMS's stated opinions. But if you see no relation, then I would suggest removing the following clauses, as it's pretty much it:
"he is entitled to his opinions just as much as anyone else. Members and supporters do not have to agree with his opinions, but should respect his right to freedom of thought and speech."

**Comment by nukeop** [comment]
I want this community to remain focused on the goal, which is supporting Stallman's reinstatement. If we make our scope too wide and too vague, we will easily get distracted and risk losing sight of the goal.

I'm also not a fan of free speech, and this letter is not about it. It's about supporting Stallman.

**Comment by nukeop** [comment]
Also we will not be changing the contents of the letter after thousands of people have signed it. It would retroactively make those signatures void. They might not agree with subsequent changes.

**Comment by dodobyte** [comment]
> I'm also not a fan of free speech,
Well I feel sorry for you.

> Also we will not be changing the contents of the letter after thousands of people have signed it.
definitely, it's frozen.

**Comment by zareami10** [comment]
You can't defend RMS without defending freedom of speech, as almost all of the attacks are about him stating his opinions. And well if you're against it, I'm kinda baffled how you'd be supporting RMS in the first place.

> Also we will not be changing the contents of the letter after thousands of people have signed it. It would retroactively make those signatures void. They might not agree with subsequent changes.

But well this is a fair point.

**Comment by nukeop** [comment]
> You can't defend RMS without defending freedom of speech, as almost all of the attacks are about him stating his opinions. And well if you're against it, I'm kinda baffled how you'd be supporting RMS in the first place.

The letter supports Stallman's freedom of speech, not anyone else's. Keep the scope narrow.

**Comment by zareami10** [comment]
> The letter supports Stallman's freedom of speech, not anyone else's. Keep the scope narrow.

What is that supposed to even mean? I'm not sure this is what you meant but that basically reads as "RMS is entitled to FoS, but well we don't care about others".

And the letter is already more than that: "he is entitled to his opinions just **as much as anyone else**."

**Comment by nukeop** [comment]
> "RMS is entitled to FoS, but others, not so much".

Yes.

**Comment by zareami10** [comment]
> > "RMS is entitled to FoS, but others, not so much".

Wow, your ideas are even cheaper than the "cancelers". And so are your actions.

**Comment by FrostKnight** [comment]
I am somewhat confused by your response zareami... whos side are you on? 

Just curious... neither, his or against?

**Comment by zareami10** [comment]
> I am somewhat confused by your response zareami... whos side are you on?
> 
> Just curious... neither, his or against?

It's actually me who is confused with the double standards brought up here.

I'm neither against nor on RMS's side. I'm just against cancelling someone merely because of their opinions, and that's the reason I have my signature here (thankfully despite the nonsense ideas of the author (I think ?), the letter still contains a note on freedom of speech).

**Comment by 6r1d** [comment]
> I'm not sure this is what you meant but that basically reads as "RMS is entitled to FoS, but others, not so much".

RMS literally stands behind FSF and Free Software. He's not "entitled", he's not some inheritor who did nothing, **he is a creator and that is why we respect him**. He knows how things can go wrong more than anyone, and for all these things, we need him onboard.

We need him to protect the idea, because this idea helped before, helps now and will help a lot more. But only if it is not destroyed now.
He is relevant like never: without him, the idea of Free Software may die off. [There are people who want to destroy it](https://medium.com/@beewithablog/open-is-cancelled-da7dd6f2aaaf), warp it and replace it with something else. And at the very least, they don't have the same experience.

[Proof RMS is Still Important](https://open.lbry.com/@Lunduke:e/RMSStillImportant:6?r=GAaJ9s3EZNYqp61oaAXUcUzgEMPmhhf1)

[In Defense of Richard Stallman](https://open.lbry.com/@Lunduke:e/DefenseofStallman:9?r=GAaJ9s3EZNYqp61oaAXUcUzgEMPmhhf1)
