### ISSUE TITLE
Bruh

### ISSUE THREAD

**Issue by test1230-lab** [rms-support-letter/rms-support-letter.github.io#3883]
This dude is a creep

**Comment by shenlebantongying** [comment]
Then you are a holy man who drink pure water and never have sex.

**Comment by test1230-lab** [comment]
I don't follow your argument. Have u read the shit he said and the allegations against him. Just doesn't seem like a good guy

**Comment by shenlebantongying** [comment]
I don't follow your argument too. Have u read what beyond what the open letter tells you? And what he did for good? Why so controversy? Why so many people want to take him down? In the same time, why so many people want to keep him?

I don't agree to everything with him, but still he at least deserve a more decent leave rather than being mobbed.

**Comment by test1230-lab** [comment]
He has been reinstated, and there is no doubt in anyone's mind that he as done a lot of good in advancing the free Software Foundation's mission. He didn't do heinous shit, just seems that maybe he isn't the best face for the programming community. With that being said I don't expect him to resign again.

**Comment by Bluesboy** [comment]
@shenlebantongying just close. Isn't an issue.

**Comment by nukeop** [comment]
> This dude is a creep

Interesting thesis. 1 rep max bench?

**Comment by 6r1d** [comment]
He is wrongly accused often enough, if not in 100% of the situations. How about that?
https://jorgemorais.gitlab.io/justice-for-rms/

**Comment by test1230-lab** [comment]
@6r1d from your article:
A true part of the story is that Stallman’s personal website has extremely liberal political opinions on sex and related subjects. A few excerpts from many years ago did defend the alleged liberty of children to have sex—even with adults—“if the child accepted it”. For example, in 2003 Stallman wrote:

"I think that everyone age 14 or above ought to take part in sex, though not indiscriminately. (Some people are ready earlier.)"

In 2006, he was skeptical of the claim that “voluntarily pedophilia” harmed children. He wrote something similar in January 2013, but within limits.

I think this speaks for itself, this is not someone I respect. I don't see how you could support this man. I am closing this issue

**Comment by FrostKnight** [comment]
Okay, he was ignorant thats all... smh...
