### ISSUE TITLE
Duplicate signatures

### ISSUE THREAD

**Issue by devenblake** [rms-support-letter/rms-support-letter.github.io#3908]
I noticed a needle in a haystack; there are two identical signatures for a Dimitri Fruchtenstein. You can confirm using `cd _data/signed && md5sum * | grep $(md5sum * | awk '{print $1}' | sort | uniq -d)` from the repo root. Spotted it from the webpage itself, mouse cursor happened to land on the right line at the right time.

Dimitri probably resubmitted their signature because they spelled their name wrong; there's a `_data/signed/Fruchtenstein.yaml` and a `_data/signed/Fruchtenstien.yaml`.

I wanted to make sure there were no other duplicate signatures so I quickly checked to make sure every link is unique: `cd _data/signed; for file in *; do cat "$file" | head -n 2 | tail -n 1 | awk '{print $2}'; done | sort | uniq -d`. There are a couple duplicates:
```
https://github.com/Arcilollo
https://github.com/Fruchtenstein
https://kernal.eu/
https://t.me/mostfa_23
```
Fruchtenstein as before and kernal.eu is expected, but also a Telegram link and a GitHub link. `https://github.com/Arcilollo` is in `arcilollo.yaml` and `lorenzoArcilollo.yaml`. `https://t.me/mostfa_23` is in `mostfa.yaml` and `mostfalmadedy.yaml`.

The name in `arcilollo.yaml` doesn't match `lorenzoArcilollo.yaml` or the associated GitHub profile and looks like a typo. The reason for the mostfa duplicate is unknown but it may have to do with one file having the name in ASCII characters and the other having the name in non-ASCII glyphs. There's no reason to suspect ill intent.

The following should probably be removed: `_data/signed/Fruchtenstien.yaml`, `_data/signed/arcilollo.yaml`, and one of `_data/signed/mostfa.yaml` and `mostfalmadedy.yaml`.

**This is three duplicate signatures in a letter that has over three thousand and there's no evidence there are any more.**

**Comment by 6r1d** [comment]
Thank you very much, @devenblake, I really appreciate your help. It will help to improve letter's credibility.
I was worried about something being suspiciously similar myself.
My commit is referenced in this issue now.
I want others to have a look and agree or disagree with which records I've removed, so I'll leave it open.

**Comment by devenblake** [comment]
It looks like there's a find-duplicates.py but I couldn't get it to work. Here's my full script:
```
printf "Outputting duplicate files\n"
md5sum * | grep $(md5sum * | awk '{print $1}' | sort | uniq -d)
printf "Outputting files with duplicate links\n"
for link in $(for file in *; do cat "$file" | head -n 2 | tail -n 1 | awk '{print $2}'; done | sort | uniq -d); do grep -Ri $link; done
```
(released unencumbered to the public domain)

**Comment by shenlebantongying** [comment]
I don't think kernal.eu is duplicated. They are people come from the same community..........

![image](https://user-images.githubusercontent.com/20123683/112741464-07740180-8f54-11eb-8398-831da36f6029.png)

**Comment by devenblake** [comment]
> I don't think kernal.eu is duplicated. They are people come from the same community..........

As I said, it's expected. Therefore, no action taken on it.

**Comment by 6r1d** [comment]
> I don't think kernal.eu is duplicated. They are people come from the same community..........

I see all three nicknames on https://kernal.eu/ :-)

**Comment by imachug** [comment]
For the record, I've updated find-duplicates.py to check both names and links. At present it returns the following:

```
$ python3 find-duplicates.py 
Ilya Popov duplicates: ['IluhaChg.yaml', 'ilya-popov.yaml']
https://kernal.eu/ duplicates: ['Cu64.yaml', 'Stnby.yaml', 'siren.yaml']
```

The first duplicate looks like an coincidence, both the first name and the surname are pretty common in Russia. The second line is from a multi-user blog.
