### ISSUE TITLE
Signature validation confusion

### ISSUE THREAD

**Issue by 6r1d** [rms-support-letter/rms-support-letter.github.io#3914]
At this point in time, we have a signature validator that fails quite often when PRs happen, and it can fail on someone else's signature while people do PRs. Someone can get to sleep and the validator failing at that time will fail everyone else's signature after.

It gets people confused about contents of their own signatures, leading to signers sharing their personal email and reducing letter's credibility (while helping the spam bots).

It happened to @teddyvn and I noticed he did at least three PRs. This is the [last one](https://github.com/rms-support-letter/rms-support-letter.github.io/pull/3903). I think we need to address that if we can.

Thank you!

**Comment by shenlebantongying** [comment]
Resolved already.
