### ISSUE TITLE
request that @cmpunches stop impersonating people

### ISSUE THREAD

**Issue by void-witch** [rms-support-letter/rms-support-letter.github.io#3916]
github user @cmpunches is attempting to impersonate people on twitter as void_witch2

the user void_witch2 on twitter was previously lord_bagira: https://web.archive.org/web/*/http://twitter.com/lord_bagira*

here is their youtube account, notice they mention "SILO GROUP LLC": https://web.archive.org/web/20210328001545/https://www.youtube.com/channel/UCYC8elg_-VBcbKOJ2eOFLaw/about

and here's their github, where they mention they work for (drum roll) silo group: https://web.archive.org/web/20210328033439/https://github.com/cmpunches

here's a tweet from lord_bagira that is now a tweet from void_witch2: (lord_bagira) https://web.archive.org/web/2020*/https://twitter.com/lord_bagira/status/1343477220627673088 (void_witch2) http://web.archive.org/web/20210328002048/https://twitter.com/void_witch2/status/1343477220627673088

if you actually care about harassment, you will ask your signatories to drop the bullshit

**Comment by void-witch** [comment]
the issue seems to have been resolved. @nukeop or @shenlebantongying feel free to delete this if you want. i understand you weren't involved in this at all

**Comment by jobbautista9** [comment]
No, we don't delete issues unless they are pure trolling or harassment. That's not really our thing. :)

**Comment by void-witch** [comment]
we may disagree, but i appreciate you sticking to your values :)

**Comment by void-witch** [comment]
reopening this as the issue clearly is not as resolved as i had thought

**Comment by void-witch** [comment]
the user is now making legal threats over, pointing out that they were attempting to impersonate me? i guess? who knows. anyway, if y'all could tell him to like, not? that would be cool
![image](https://user-images.githubusercontent.com/51172302/112743249-99cfd180-8f63-11eb-8ab9-6829dd0d3274.png)
![image](https://user-images.githubusercontent.com/51172302/112743252-9d635880-8f63-11eb-9299-7bc8c5458c05.png)

**Comment by jobbautista9** [comment]
@cmpunches @void-witch Both of you, please stop for a moment. Haven't you considered that somebody else is trying to impersonate both of you? The Twitter account was created in March 2021. Somebody could be false-flagging.

**Comment by void-witch** [comment]
the twitter account was created in december of 2020, as you can see in the first screenshot, and has been using chris' handle (lord_bagira) for 4 months now. this handle has been used as chris' youtube channel name as well, which you'll see in the links i posted when creating this issue thread

**Comment by jobbautista9** [comment]
I'd like to note that the account could've deleted in some point in 2020, then created under the same username in 2021. Which is why we're seeing today that the accounts (lord_bagira and void_witch2 are separate accounts currently as of writing) are created in March 2021.

I'm not familiar with Twitter much, but shouldn't it prevent deleted and old usernames from being recreated?

I'm going to defer to @nukeop on this one.

**Comment by void-witch** [comment]
@jobbautista9 look in the screenshot and the archive link, both of them show that the account was created in december of 2020, and has a tweet with the same tweet id under both usernames. i.e. this was a tweet made by lord_bagira in december of 2020: https://web.archive.org/web/20201228084157/https://twitter.com/lord_bagira/status/1343477220627673088

this is that exact same tweet, with the same content, and the same id "1343477220627673088" under the username void_witch2: http://web.archive.org/web/20210328002048/https://twitter.com/void_witch2/status/1343477220627673088

this is demonstrably 100% the same account, that is the *only* way that the same tweet can exist under two different usernames. you'll notice that the tweet is now deleted, but that second archive link was made on march 28th (within the past few hours, actually). this means that whoever runs the account (now Equus_Rufus) deleted the tweet within the past few hours

i'm going to close this, so that the drama comes to an end. however, i'd prefer that it be locked and unaltered in case there are any legal issues that come from this

**Comment by jobbautista9** [comment]
Should've locked this a long time ago :)
