### ISSUE TITLE
We have more signatures and stars. The community supports RMS

### ISSUE THREAD

**Issue by bnainar** [rms-support-letter/rms-support-letter.github.io#3948]
### open letter
stars: 575
fork: 2.1k
translated languages: 17
**signatures:** 2895

### support letter
stars: 1.9k
fork: 3.8k
translated languages: 26
**signatures:** 4080

The community has spoken. Majority of us want RMS to stay. You don't need to agree with RMS, because this issue is much greater than RMS, they target the free software movement and our freedom of expression. I signed this letter, even though I disagree with RMS on many issues.

**Comment by 6r1d** [comment]
> they target the free software movement and our freedom of expression

Some time ago, I'd tell you that you are exaggerating. Now, though, with evidence like "[Open is cancelled](https://medium.com/@beewithablog/open-is-cancelled-da7dd6f2aaaf)", I sadly have to agree: you are completely right there.

**Comment by KOLANICH** [comment]
IT’S *NEO*LIBERALS ON THE MARCH GET IN THE CAR

**Comment by KOLANICH** [comment]
They have stopped to accept signatures via PRs (is it an effort to make comparison more difficult?), also count of forks is not an approximate of a count of PRs, since some people don't understand difference between a "star" and a "fork" and create unneeded forks and since many prefer to delete forks after their prs are merged, and count of stars is not count of signatures.

**Comment by jobbautista9** [comment]
> IT’S _NEO_LIBERALS ON THE MARCH GET IN THE CAR

Funnily enough, true neoliberals won't care about this. After all they are against populism.

**Comment by KOLANICH** [comment]
I don't think that there is such a thing as a true `neoliberal`, because `neoliberal`s are in fact not liberal and the word `neoliberal` is just a purportedly misleading euphemism for a `fascist`, which has falled out of favour after WW2.

**Comment by bnainar** [comment]
neoliberal, liberal, libertarian - all 3 are different

**Comment by ItsukiNakano** [comment]
> The community has spoken.

![image](https://user-images.githubusercontent.com/81519284/112754631-a137bf00-8fe5-11eb-9fb2-5eba0d71b196.png)

**Comment by teunissenstefan** [comment]
> > The community has spoken.
> 
> ![image](https://user-images.githubusercontent.com/81519284/112754631-a137bf00-8fe5-11eb-9fb2-5eba0d71b196.png)

"Russiand"
This is quite obviously 100% accurate. Nevermind the fact that you joined 15 minutes ago.

**Comment by shenlebantongying** [comment]
@ItsukiNakano Creates a new account just to post this. You must be angry for RMS being supported but don't actually that kind of freedom. LOL

**Comment by jobbautista9** [comment]
Aba aba, I didn't know that Filipinos are Russian. Anyone wants to join me in establishing the Philippine Soviet Socialist Republic?

**Comment by nukeop** [comment]
bye bye

**Comment by KOLANICH** [comment]
@ItsukiNakano, How large is the share of votes for `rms-open-letter` that was collected by mail? Can `rms-open-letter` folks proove the votes were by real persons and not forged by the ones collecting them? I require them to publish all the mails they registered as votes with their DKIM signatures and proofs that the mails belong to real developers with well-known recognized contributions to open-source.

**Comment by KOLANICH** [comment]
@jobbautista9, don't you know that Etrusc means "it's Russians" in Russian ? ;)

**Comment by nukeop** [comment]
> @ItsukiNakano, How large is the share of votes for `rms-open-letter` that was collected by mail? Can `rms-open-letter` folks proove the votes were by real persons and not forged by the ones collecting them? I require them to publish all the mails they registered as votes with their DKIM signatures and proofs that the mails belong to real developers with well-known recognized contributions to open-source.

Our process is 100% transparent. Everything is public, down to email headers.

**Comment by KOLANICH** [comment]
@nukeop, what was the deleted comment about? I haven't received it by email.

**Comment by teunissenstefan** [comment]
I forgot what he said but he attached [this image](https://user-images.githubusercontent.com/81519284/112754631-a137bf00-8fe5-11eb-9fb2-5eba0d71b196.png)

**Comment by KOLANICH** [comment]
@teunissenstefan, I saw the image, but I am not sure that that comment was deleted. That one has disappeared, but the marking about comment deletion by a moderator is after it was mentioned.

**Comment by nukeop** [comment]
It was pointless spam I don't want to see here

**Comment by shenlebantongying** [comment]
@nukeop maybe hide or fold better than delete?

**Comment by nukeop** [comment]
There's no value in keeping it here imo.

**Comment by SpheeresX** [comment]
I made a website that shows how many more signatures rms-support-letter has than rms-open-letter. https://rms-letters.spheeresx.repl.co/

**Comment by shenlebantongying** [comment]
@SpheeresX I suggest you change `2860` to  `2812+48 (orgs)+16(initial signers)` for more clear info.

**Comment by SpheeresX** [comment]
@shenlebantongying I'll try to add that tomorrow, thanks!

**Comment by srid** [comment]
> this issue is much greater than RMS

Here are a couple of links for folks trying to comprehend what this means:

- https://reclaimthenet.org/
- https://newdiscourses.com/tftw-critical-race-theory/

**Comment by kkmzero** [comment]
> > they target the free software movement and our freedom of expression
> 
> Some time ago, I'd tell you that you are exaggerating. Now, though, with evidence like "[Open is cancelled](https://medium.com/@beewithablog/open-is-cancelled-da7dd6f2aaaf)", I sadly have to agree: you are completely right there.

Regarding that blog post, justice is not ambiguous nor open for re-definition, maybe they search for other word. I don't really like this idea of replacing freedom by ambiguous ideological loopholes, especially when we talk about focus of FSF in future, free software and software licenses dealing with FOSS.

If you want to exclude military use or use by govt institutions, look for legal ways, add specific clauses dealing with this issue. If you want to waste your resources and micromanage your community and its behavior, adopt CoC. What else can there be done?

Personally, I miss times when you could write software for fun, or when you were looking for solutions to your problems in computing, when you were treated as individual doing his/hers job. I don't get why every tech project/org/company nowadays acts like political party and the social aspect of it, or your social credit, is more important than work being done. I just hope FSF remains reliable in issues of freedom in computing, hopefully.

**Comment by jobbautista9** [comment]
By the way, this seems something that should be converted into a discussion, since there's no issue here at all. Any objections?

**Comment by KOLANICH** [comment]
I feel like it is not beneficial for this project and just introduces 2 places to look at. In fact I don't even know any real use-cases for them issues cannot handle, except just creating a deducated place for offtop threads.
