### ISSUE TITLE
Support Richard Stallman

### ISSUE THREAD

**Issue by OlegKapust** [rms-support-letter/rms-support-letter.github.io#4099]
Oleg Kapustin
https://github.com/OlegKapust

**Comment by shenlebantongying** [comment]
If you want to sign, pls comment at #837 rather than separate issue.

**Comment by keithbowes** [comment]
Whoa, did RMS use the wrong pronoun or something?

**Comment by shenlebantongying** [comment]
Sumbitted https://github.com/rms-support-letter/rms-support-letter.github.io/commit/1f793bfcbad45c2d5af6a562ef15d5495cb48ca3
