### ISSUE TITLE
I support Richard Stallman

### ISSUE THREAD

**Issue by vagabundoscuro** [rms-support-letter/rms-support-letter.github.io#4101]
Richard Stallman has my support.

**Comment by shenlebantongying** [comment]
Are you going to sign or just talk. If you want to sign, pls comment at https://github.com/rms-support-letter/rms-support-letter.github.io/issues/837

**Comment by shenlebantongying** [comment]
https://github.com/rms-support-letter/rms-support-letter.github.io/pull/4127
