### ISSUE TITLE
Robot delete log

### ISSUE THREAD

**Issue by shenlebantongying** [rms-support-letter/rms-support-letter.github.io#4134]
@hexherhide666 for those suspicious movements with a 1 day account
https://github.com/rms-support-letter/rms-support-letter.github.io/pull/4121
https://github.com/rms-support-letter/rms-support-letter.github.io/pull/4127
https://github.com/rms-support-letter/rms-support-letter.github.io/pull/4123
https://github.com/rms-support-letter/rms-support-letter.github.io/pull/4113
[nsfw] https://github.com/hexherhide666/brander-Hyde-Trump/issues/2

This account is probably fake, and realted to @hexherhide666
https://github.com/nikitalocalhost
@nikitalocalhost 
thus revoked https://github.com/rms-support-letter/rms-support-letter.github.io/pull/4113

This account may also be related to him, but not yet begin to pr
(forked this repo and followed by @hexherhide666)
https://github.com/anon72

**Comment by bnainar** [comment]
That's not NSFW, that is NSFL

**Comment by shenlebantongying** [comment]
@nukeop It seems only you can ban him

**Comment by shenlebantongying** [comment]
Removed @anon72 , since new account is impossible to be accidentally be discovered by @hexherhide666.


https://github.com/rms-support-letter/rms-support-letter.github.io/commit/9ecf96cf7cb755cf96c8067c153793f0183c7798

**Comment by nukeop** [comment]
Lol, what?

**Comment by nukeop** [comment]
I banned this guy but I can't grasp what happened here.

**Comment by shenlebantongying** [comment]
He was like a creepy ghost, put random words on every merger after me............

**Comment by nukeop** [comment]
Still not sure if it's a regular schizo or an AI.

**Comment by shenlebantongying** [comment]
Same guy → https://github.com/lionelPhaeton
https://github.com/lionelPhaeton

**Comment by nukeop** [comment]
😄

**Comment by shenlebantongying** [comment]
Same guy → https://github.com/rms-support-letter/rms-support-letter.github.io/pull/4224

You should unsubscribe this, I just keep a tracker here.

**Comment by shenlebantongying** [comment]
Remove invalid troll https://github.com/rms-support-letter/rms-support-letter.github.io/commit/dc0bcc484ad1f3a0f9781456be3556302fc6dff5

**Comment by shenlebantongying** [comment]
Deleted https://github.com/rms-support-letter/rms-support-letter.github.io/pull/4702

**Comment by shenlebantongying** [comment]
https://github.com/rms-support-letter/rms-support-letter.github.io/pull/4737
