### ISSUE TITLE
Beware of harassment and doxxing

### ISSUE THREAD

**Issue by yagehu** [rms-support-letter/rms-support-letter.github.io#4258]
Came across [this repo](https://github.com/sticks-stuff/highlight-RMS-supporters) by chance. It's just JavaScript that highlights people who've signed the support letter, but the undertone of the project irked me. It got me worried that malicious users may harass and dox people who've signed the support letter.

*Do not harass the repo owner.* If you have concerns about the intent of the repo, simply report it to GitHub.

**Comment by jobbautista9** [comment]
Thanks. I reported the user to GitHub. Let's see what happens.

**Comment by stayen** [comment]
Same, let's see what follows.

**Comment by Crazily** [comment]
Violated the GDRP and my information should be removed from it. But **it** merged my PR and then their bot just added it right back :(

**Comment by DanInSpace104** [comment]
@Crazily i want to report these repos, but don't know how to do it properly. Can you please explain how to do it?

**Comment by dodobyte** [comment]
Reported the owner.
https://github.com/contact/report-abuse?report=sticks-stuff+%28user%29

**Comment by 6r1d** [comment]
> Thanks. I reported the user to GitHub. Let's see what happens.

I am worried. Is that an abuse by GitHub standards? Yes, it looks like a "witch hunt" already, but do we have a right to report it? Can anyone tell if we do? @cmpunches , you know these better, can you comment, please?

**Comment by dodobyte** [comment]
See the `names.json` file. Our names and profile urls are shared without permission for exposing purpose. I am pretty sure it's a violation of my privacy.

**Comment by DanInSpace104** [comment]
@6r1d even if it is not abuse, did you give permissons to use yor personal data? It violates GDPR

**Comment by cmpunches** [comment]
Grey area.  He's doxxing users but not providing raw data file.  I would report.

I keep telling folks this -- there aren't alot of legals for cancel culture tactics -- the only way to deal with those kinds of strategies is to make the effort more expensive.  

The bright side is that they're low information and emotionally unstable by trend, most of them are not very informed about what's going on; this is a second wave of flying monkeys who are going to be predominantly focused on dog-whistles and virtue signaling, so, simply cataloging them in a tit-for-tat fashion in a very visible way is surprisingly effective in my experience.  It would get exhausting unless it is technology-aided, and it wouldn't be my call to make now do I have the time to invest in doing it beyond adding names as I get harassed.

**Comment by astrophena** [comment]
This is hillarious:

![Screenshot_20210329_093936](https://user-images.githubusercontent.com/58525038/112796518-c292bc80-9072-11eb-882c-4fc64241b11a.jpg)

**Comment by jobbautista9** [comment]
This is why "woke" people shouldn't code.

**Comment by cmpunches** [comment]
It's not that hard to code what he's trying to build, he'll get it eventually.  Low threat, but this is a trending effort, and that's the threat.   I'm seeing alot of career targeting on twitter.

**Comment by nukeop** [comment]
We already have an issue dedicated to this. Please don't give this guy any more attention.

**Comment by Yegg12** [comment]
> 
> 
> Grey area. He's doxxing users but not providing raw data file. I would report.
> 
> I keep telling folks this -- there aren't alot of legals for cancel culture tactics -- the only way to deal with those kinds of strategies is to make the effort more expensive.
> 
> The bright side is that they're low information and emotionally unstable by trend, most of them are not very informed about what's going on; this is a second wave of flying monkeys who are going to be predominantly focused on dog-whistles and virtue signaling, so, simply cataloging them in a tit-for-tat fashion in a very visible way is surprisingly effective in my experience. It would get exhausting unless it is technology-aided, and it wouldn't be my call to make as I am not affiliated nor do I have the time to invest in doing it beyond adding names as I get harassed.
> 
> My recommendation is to start listing harassers and tying names where possible in a google indexed manner.



> 
> 
> It's not that hard to code what he's trying to build, he'll get it eventually. Low threat, but this is a trending effort, and that's the threat. I'm seeing alot of career targeting on twitter.

Hello again! I've noticed that you've used the incorrect pronouns here as well, so as a just in case (and for anyone in this thread that hasn't seen the other one), they actually use they/them pronouns! Again, not knowing is fine, but please try using the correct pronouns from now on!
