### ISSUE TITLE
Social media preview is a license violation

### ISSUE THREAD

**Issue by marcan** [rms-support-letter/rms-support-letter.github.io#4310]
The social media preview uses the cover photo from "Free as in Freedom", but that book is licensed under the GFDL. The GFDL and the GPL are incompatible, and therefore using that cover photo in this website is a violation of both licenses.

The image is also available under CC-BY-SA 3.0 (because it was used on Wikipedia, and the FSF released a new GFDL version with a backdoor that allowed CC-BY-SA 3.0 relicensing), but that license is also not compatible with the GPL.

**Comment by 6r1d** [comment]
It's funny how you attack a social preview image instead of arguing facts. So far, open-letter was closed to communication and removed lots of issues, which tells a lot. I'll tell the image authors about this situation if they haven't seen it already.

**Comment by kitsunyan** [comment]
IANAL.

Since the cover photo is derivative work and the original image is GFDLed, the cover image should be GFDLed as well. I suppose, it should be enough to just mention somewhere (e.g. README) that "cover photo is under GFDL, the rest of the website is under GPL".

Regarding mixing GPLed and GFDLed data, I don't see any problems in publishing GFDLed artwork on GPLed website. Using some image on a website doesn't make derivative work, as well as GPLed website is not "statically or dynamically linked" (which are computing terms) with the artwork.

**Comment by jobbautista9** [comment]
Thanks for opening this issue @marcan.

IANAL as well, but I think the CC-BY-SA-3.0 allows upgrading its license to CC-BY-SA-4.0, which would be compatible with the GPLv3.

**Comment by marcan** [comment]
GFDL has a very long list of requirements for redistributing derivative works. It is not sufficient to say a derivative work is GFDLed to be able to redistribute it, read the license text for more details.

IANAL, so I don't know if the CC-BY upgrade path is a valid path to GPL compatibility.

**Comment by nukeop** [comment]
I will add a note stating that images in assets are licensed under CC BY-SA 3.0.

**Comment by marcan** [comment]
CC BY-SA requires attribution, and just putting it in the source code of the site isn't enough for that, since it isn't visible in the release version. It would have to be at the very list visible in the website, if not on the image itself.

**Comment by nukeop** [comment]
I added attribution plus license clarification to the readme, thanks for notifying us.

**Comment by kitsunyan** [comment]
> valid path to GPL compatibility

There is no "GPL compatibility" problem. The fact the image is referred from website by `<meta>` link neither produces derivative work, nor "program linking". The fact that image is hosted at the same repository doesn't enforce any requirements as well.

The only problem I see is that the cover image is a derivative work by itself, and there might be some requirements applied to the image only (like attribution, etc).

**Comment by gorshunovr** [comment]
From the first edition of the [book](https://archive.org/details/freeasinfreedomr00will/page/n7/mode/2up):
`Cover photograph of Richard Stallman (c) Sam Ogden/Photo Researches, Inc., and can not be used without permission.`
Sam's webpage is [here](https://www.samogden.com/contact), and Photo Researches, Inc. is now [Science Source](https://www.sciencesource.com/about-us). I'm composing and sending a request to them.

**Comment by nukeop** [comment]
> From the first edition of the [book](https://archive.org/details/freeasinfreedomr00will/page/n7/mode/2up):
> `Cover photograph of Richard Stallman (c) Sam Ogden/Photo Researches, Inc., and can not be used without permission.`
> Sam's webpage is [here](https://www.samogden.com/contact), and Photo Researches, Inc. is now [Science Source](https://www.sciencesource.com/about-us). I'm composing and sending a request to them.

There's no need to, it's relicensed on WIkipedia.
