### ISSUE TITLE
Opposition is now running shadow campaign, which has gone viral

### ISSUE THREAD

**Issue by cmpunches** [rms-support-letter/rms-support-letter.github.io#4337]
Opposition is now running a shadow campaign using tertiary connections, which has gone viral.  Have seen 2 waves so far; Some of them are targeting signers for doxxing and career smearing purposes.

Recommending a strategy for increasing processing overhead for the opposition camp to slow it down and divert.

**Comment by VentGrey** [comment]
Do you have any proof to backup this claim? If so, it should be important to keep activists informed to prevent cancellations from under the hood and find a way to proceed carefully.

**Comment by cmpunches** [comment]
> Do you have any proof to backup this claim? If so, it should be important to keep activists informed to prevent cancellations from under the hood and find a way to proceed carefully.

There is a group of folks observing it on freenode.  I have personally observed it.  I'm not sure how to model it to document it.

**Comment by 6r1d** [comment]
Is this repo marking us in red related, @cmpunches ?
https://github.com/sticks-stuff/highlight-RMS-supporters

**Comment by cmpunches** [comment]
Yes that user was linked to in a previous twitter conversation where he volunteered in a group trying to deliberate ways to damage signers.  It's as malicious as it looks and there are going to be 10s of thousands if this escalates.

**Comment by nukeop** [comment]
People who harass others on Twitter never make hiring decisions. They're unemployed basement dwellers or teenagers. Intimidation tactics work because you're afraid of them. Remember that they're just playing tough on Twitter.

**Comment by nukeop** [comment]
This is stage 2 of grief: anger. That's how they cope with defeat.

**Comment by cmpunches** [comment]
Fair enough @nukeop there may be an element of that.  After the sensationalism wears off we'll see the waves die out because they are being driven by folks who are caught up in the moment for a virtue signal and immediate supply....ok, I see it, yeah.

The timing of it going viral is the concern here.  I believe it's being heated up by a shadow campaign.  If that's the case it could become sustained or much larger.

**Comment by nukeop** [comment]
Don't get baited into wasting your time and energy on arguing. We have a goal we need to work on achieving.

**Comment by Yegg12** [comment]
> 
> 
> Yes that user was linked to in a previous twitter conversation where he volunteered in a group trying to deliberate ways to damage signers. It's as malicious as it looks and there are going to be 10s of thousands if this escalates.

Hello! I just want to say their pronouns are actually they/them! I understand you might've not known before, but i hope this clears it up!

**Comment by nukeop** [comment]
We will no extend common courtesy to people who are creating targeted harassment tools.

**Comment by Tyil** [comment]
> We will no extend common courtesy to people who are creating targeted harassment tools.

By not extending any courtesy you're no better than the anti-rms people. Dividing the groups even further isn't helping anyone in the long run, all you're doing is giving them more reasons to hate us, reasons which do exceptionally well in today's media, which loves to sensationalize hatred.

**Comment by jobbautista9** [comment]
They may be harassing us, but we still should be civil. There's a Filipino proverb for this: "If someone throws a rock to you, throw them bread."
