### ISSUE TITLE
Change the org picture

### ISSUE THREAD

**Issue by Kreyren** [rms-support-letter/rms-support-letter.github.io#4378]
The current org picture:
![image](https://user-images.githubusercontent.com/11302521/112812959-faebc800-907d-11eb-9927-318bbfa5a874.png)

In my humble opinion damages the credibility of this effort as the anti-RMS party claims that "RMS psycafans are enabling this unacceptable behavior" and could portrait those who are signing this document as a part of the "Emacs Cult" to discredit us.

> We are calling for the removal of the entire Board of the Free Software Foundation. These are people who have enabled and empowered RMS for years. They demonstrate this again by permitting him to rejoin the FSF Board. It is time for RMS to step back from the free software, tech ethics, digital rights, and tech communities, for he cannot provide the leadership we need. We are also calling for Richard M. Stallman to be removed from all leadership positions, including the GNU Project. -- https://rms-open-letter.github.io/

Thus i propose to change it on something more politically appropriate.

**Comment by nukeop** [comment]
Don't be so humorless.

**Comment by Kreyren** [comment]
> Don't be so humorless.

I have to be, the less emotions there are in politics the more things can be done as the other party can't use them agains us which is what they are doing now.

**Comment by jobbautista9** [comment]
I can understand what you're saying, but that's the problem. Humor is no longer being encouraged, even if harmless. We need to change that.

**Comment by Kreyren** [comment]
> Humor is no longer being encouraged, even if harmless. We need to change that.

I think that it's malpractice in politics the more humorous you are the less credible and incompetent it makes you look.

**Comment by Kreyren** [comment]
and i don't believe that we can afford humor exchanged for a credibility atm.

**Comment by nukeop** [comment]
It's just a picture, we're already being taken very seriously as seen by the number of various attacks. I wouldn't worry about it. We already have a very professional social preview image for this purpose anyway.
