### ISSUE TITLE
Can't sing from telephone

### ISSUE THREAD

**Issue by VictorNRA** [rms-support-letter/rms-support-letter.github.io#442]
How can i singing using phone? 
Please, sing me https://github.com/VictorNRA

**Comment by nekonee** [comment]
You can edit index.md with web gui and add yourself this way.
Do you want to give it a try or do you want me to add you?

**Comment by VictorNRA** [comment]
It would be great if you add me! Tnx!

**Comment by majestrate** [comment]
you shouldn't modify index.md it's being auto generated now because of the volume

you can use this link to add your signature in a file:

https://github.com/rms-support-letter/rms-support-letter.github.io/new/master/_data/signed

name of file: `<your-username-goes-here>.yaml`

contents of file:

```
name: <your name here>
link: <link to your profile or site>
```

**Comment by KOLANICH** [comment]
>How can i singing using phone?
>Please, sing me https://github.com/VictorNRA

We cannot help you. Neither Yamaha can. There is no mobile version of Vocaloid software.

**Comment by SViN24** [comment]
you can if you use desktop mode on your browser.
it is however a bit of a pain

**Comment by VictorNRA** [comment]
Thanks for all. I hope I was did all at best!

**Comment by Motophan** [comment]
Can u add me too +1

**Comment by imachug** [comment]
@Motophan Please add a comment here: #837.

Closing to not misdirect future signatories.
