### ISSUE TITLE
But what about veganism?

### ISSUE THREAD

**Issue by clort81** [rms-support-letter/rms-support-letter.github.io#4433]
How many people in the OSI, Red-Hat are non-vegan?  Should they be allowed to hold a position of authority if they are not?

I'm sure I don't need to explain in detail why meat eaters can not be tolerated in an official position.

**Comment by nukeop** [comment]
Don't spam please

**Comment by 6r1d** [comment]
Lighthearted parodies and joke articles on social media like https://ultralux97.medium.com/stallman-must-be-removed-a3061b09fb22 are welcome, though!

**Comment by clort81** [comment]
But it's informative too.  You can pick some other issue that the RMS accusers aren't sufficiently virtous on and turn the tactic against them, or at least use it to illustrate how unrelated political stances should be irrelevant to the job.
