### ISSUE TITLE
Are you drunk?

### ISSUE THREAD

**Issue by bobbigmac** [rms-support-letter/rms-support-letter.github.io#4538]
Someone wrote "philosophical underpinnings, and pursuing the objective truth and linguistic purism" and thought that was okay. Literally makes me wonder who is behind this, because linguistic purism is just some supremacy bullshit.

**Comment by shenlebantongying** [comment]
Hahahaha, the letter was finished in a rush to counter the open letter. However, if you focus on one or two words, you might miss the whole point of this letter.

**Comment by bobbigmac** [comment]
I was involved with white supremacists 20 years ago, this is exactly how they write, and exactly how they argue against individual points in their work. For anyone who is involved with this letter, whatever you think about RMS, there are some darker elements in our dev communities, and they're pretty transparent right now.

**Comment by shenlebantongying** [comment]
If you look closely, you will realize that the open letter is also a "supremacists" as you defined. I would say this is a tragedy for this community, since both letter may help split up the community.

They are not "transparent" at all, they censored every trial to communicate

Here are a backup of some censorship https://github.com/rms-support-letter/rms-support-letter.github.io/issues/175

They give FSF and RMS no space to open talk

![image](https://user-images.githubusercontent.com/20123683/112862762-15c13b00-9084-11eb-8fe8-79f401229eb5.png)

**Comment by BlueFlo0d** [comment]
Those are orthogonal issue. What about let's burn all Hegel's books and revoke his PhD because he supports monarchy.

**Comment by imachug** [comment]
I understand your concerns about 'linguistic purism' -- these particular two words could be phrased better. I think what the author really meant is keeping the language as straightforward as possible to prevent any misunderstandings, but I might be wrong.

**Comment by clort81** [comment]
The tactic of attaching or redefining labels/words to mean something different than they once did, in order to achieve a political agenda is a quite commonplace tactic.

I'll leave it to the readers to consisder for themselves what instances of this they can think-of.

**Comment by Bluesboy** [comment]
I think attacking not only one person, but whole FSF board because RMS said that using words "schmu" for "she" and "zaza" instead of "papa" is silly, just ridiculous.

**Comment by nukeop** [comment]
Bye retard

**Comment by cmpunches** [comment]
> I was involved with white supremacists 20 years ago, this is exactly how they write, and exactly how they argue against individual points in their work. For anyone who is involved with this letter, whatever you think about RMS, there are some darker elements in our dev communities, and they're pretty transparent right now.

@bobbigmac my favorite part of your complaint is how you used it as a transparent device to unsuccessfully dehumanize a group you disagree with while laughably trying to associate it with "white supremacy" in the same stroke and still somehow expected to be taken seriously.

I suspect that you did not want to be taken seriouslly, and were instead hoping to get some visceral reaction you could link to in your home camp to say "see?", without letting on that you were just here to break your verbal fists on some flabby abdominal pillows during a fishing expedition for a little supply?

Well, you didn't get that supply.

Do you have a grievance worded in a way that doesn't destroy its own credibility by the nature of its expression? I'm sensing a person who has not properly researched their opinions and is instead chasing dog whistles.
