### ISSUE TITLE
GNU Kind Communications Guidelines

### ISSUE THREAD

**Issue by dzhigit1** [rms-support-letter/rms-support-letter.github.io#4686]
Adopt GNU Kind Communications Guidelines? https://www.gnu.org/philosophy/kind-communication.html

**Comment by shenlebantongying** [comment]
This is just a place for signatures plus low volume communication.

What to adopt?

**Comment by franpoli** [comment]
The GNU guidelines looks like something we could have in the [code of conduct section](https://github.com/rms-support-letter/rms-support-letter.github.io/community) of the community profile of this repository. Having it could demonstrate how civilized we are.

**Comment by nukeop** [comment]
This project will not have a code of conduct. We can adopt the GNU guidelines as a polite recommendation to stay civil, however I don't want to enshrine it in the repo in any way.

The only "code of conduct" I would ever consider adopting is this: https://sqlite.org/codeofethics.html

**Comment by ExceptionallyHandsome** [comment]
> The only "code of conduct" I would ever consider adopting is this: https://sqlite.org/codeofethics.html

Let's take a look...

> Do not commit adultery. 

Come on.

>  Honor all people. 

Even SJWs?

>  Chastise the body. 

Kinky.

>  Do not become attached to pleasures. 

You're not taking my Steam account from me, you hear? Also, porn.

>  Visit the sick. 

But the quarantine? 

>  Be a stranger to the world's ways. 

Stallman's anthem.

>  Love your enemies. 

Even SJWs?

>  Be not lazy. 

Laziness is a great programming concept. I'm not casting it away.

>  Attribute to God, and not to self, whatever good you see in yourself. 

My abs and programs are _mine_.

> Fear the Day of Judgment.
> Be in dread of hell.
> Keep death daily before your eyes. 

And they call _me_ pessimist...

>  Recognize always that evil is your own doing, and to impute it to yourself. 

But what if it's SJW's? Is God SJW?

>  Do not love much talking. 
>  Speak no useless words or words that move to laughter. 
>  Do not love much or boisterous laughter. 

You can't do this to me.

>  Obey in all things the commands of those whom God has placed in authority over you even though they (which God forbid) should act otherwise, mindful of the Lord's precept, "Do what they say, but not what they do." 

Even if they're SJWs?

>  Love chastity. 

Come oon!

>  Hate no one. 

Not even SJWs?

>  Pray for your enemies in the love of Christ. 

Even for SJWs? They're beyond even God's help, but I'll take your word for it.

>  Make peace with your adversary before the sun sets. 

Have we failed?

---

With that in mind, I think fair to say that this one does not quite suit us. I mean, even Stallman has had sex.

How about Ruby's CoC?

> This document provides community guidelines for a safe, respectful, productive, and collaborative place for any person who is willing to contribute to the Ruby community. It applies to all “collaborative space”, which is defined as community communications channels (such as mailing lists, submitted patches, commit comments, etc.).

    Participants will be tolerant of opposing views.
    Participants must ensure that their language and actions are free of personal attacks and disparaging personal remarks.
    When interpreting the words and actions of others, participants should always assume good intentions.
    Behaviour which can be reasonably considered harassment will not be tolerated.

**Comment by BeyondMagic** [comment]
> Having it could demonstrate how civilized we are.

A CoC doesn't demonstrate that, the people here demonstrates that.

> How about Ruby's CoC?

```
Participants will be tolerant of opposing views.
Participants must ensure that their language and actions are free of personal attacks and disparaging personal remarks.
When interpreting the words and actions of others, participants should always assume good intentions.
Behaviour which can be reasonably considered harassment will not be tolerated.
```

That is basically what a civilized society needs to do, no one needs a file with sets of rules saying that.

**Comment by daveflr** [comment]
> The only "code of conduct" I would ever consider adopting is this: https://sqlite.org/codeofethics.html
Holy **** is that for real? sure that sqlite org was not compromised and someone else posted that... thing ?

**Comment by jobbautista9** [comment]
Their "scope of application" doesn't require its members to follow The Rule, so it's more like an advice to happy productiveness rather than a code of conduct.

**Comment by nukeop** [comment]
You guys need more compassion.
