### ISSUE TITLE
You might not want to be associated with Joshua Conner Moon

### ISSUE THREAD

**Issue by ghost** [rms-support-letter/rms-support-letter.github.io#4716]
Joshua Conner Moon is the owner of [Kiwi Farms](https://en.wikipedia.org/wiki/Kiwi_Farms). Feel free to read the Wikipedia article to be prepared.

He has called Obama "The N-word in chief" [source](https://archive.fo/uwZNR)
He has shown belief in "White genocide" [source](https://archive.is/HAHnL)
He has advocated for Muslim genocide [source](https://archive.fo/GZoas)
He has said he'd rather let refugees die than offer them his spit to hydrate [source](https://archive.is/pchH0)

I doubt you want to associate yourself with this person. Up to you.

**Comment by PVNFU-28** [comment]
ok and

**Comment by bnainar** [comment]
It's been 6 minutes since the Issue Author created this issue, and he/she deleted the account within 6 minutes. Troll?
