### ISSUE TITLE
Well done, Translators

### ISSUE THREAD

**Issue by bnainar** [rms-support-letter/rms-support-letter.github.io#4747]
Our letter is translated into 28 languages!!(compared to that one's 17). It seems we are more "inclusive" than those SJWs arguing for CoC with "inclusiveness" lol. Thanks to all the Translators for helping us reach the message across languages. 

It seems README.md pages aren't translated to as many languages as you've done for the letter. Also for those translated the README.md page, update to include the LICENSE section

Thanks

**Comment by jobbautista9** [comment]
> update to include the LICENSE section

This has already been discussed in #3714. It's not required to translate the licensing notice, but they can do so if they wish (like I did in the Tagalog README)

**Comment by Bluesboy** [comment]
> It seems index.md pages aren't translated to as many languages as you've done for the letter. Also for those translated the 

You mean README.md ?

**Comment by bnainar** [comment]
Yes 😅

**Comment by hinell** [comment]
Please close this issue.
