### ISSUE TITLE
Problem with the letter

### ISSUE THREAD

**Issue by avgolubev** [rms-support-letter/rms-support-letter.github.io#4768]
Hello, everyone. 
The problem is that Richard Stallman is one of the great programmers 
and you a handful of pathetic no names, who instead of programming are engaged in nonsense.

Apparently tolerasty has burned your brain and you are not interested in anything more than such lampoons.

**Comment by nukeop** [comment]
Did you want to post it here? https://github.com/rms-open-letter/rms-open-letter.github.io

**Comment by avgolubev** [comment]
@nukeop No, it's okay, I wanted to send this to Stallman's opponents.

**Comment by 6r1d** [comment]
> @nukeop No, it's okay, I wanted to send this to Stallman's opponents.

Congratulations, you just told it to the Stallman's supporters.
