### ISSUE TITLE
FSF decided to stand up for RMS.

### ISSUE THREAD

**Issue by dodobyte** [rms-support-letter/rms-support-letter.github.io#4840]
I think we should all donate even a small amount.
https://twitter.com/fsf/status/1376714994721689601
https://my.fsf.org/donate

**Comment by greenhorse-effect** [comment]
Twitter needs nonfree JS, here's alternative URL: https://nitter.snopyta.org/fsf/status/1376714994721689601

**Comment by Vaporeon** [comment]
Gee those twitter replies are disgusting. How can people be so horribly misinformed and continue to spread an easily debunked lie in regards to what Stallman said in 2019?

**Comment by rldmt** [comment]
Probably the useful idiots that populate the twitter ecosystem will forget as soon as they find another victim haha.
