### ISSUE TITLE
It's not over yet, they're still trying to attract signatories:

### ISSUE THREAD

**Issue by cmpunches** [rms-support-letter/rms-support-letter.github.io#4898]
https://twitter.com/mmillions/status/1376882475041964035

They are collecting signatures in secret email threads now.  I'm sure it's "totally a reliable process that we aren't misusing to pad our numbers, we swear".  If they'll lie in their campaign about the material facts, they'll lie about their signatories, too, so, we need to drive to continue as we have been -- if you need sleep, get sleep, and carry on the effort!

We need people to continue to promote this letter and attract signers.  We need more international reach.  We need more corporate reach where possible.

**Comment by nukeop** [comment]
Without transparency the whole process is illegitimate.

**Comment by cmpunches** [comment]
> Without transparency the whole process is illegitimate.

@nukeop could not agree more, but, remember they're running a mixed-media viral campaign effort, so, if enough people believe it, it may as well be true.

**Comment by cmpunches** [comment]
At this point we have almost twice as many signatures.  We gotta keep climbing so they don't close the gap.

**Comment by hinell** [comment]
If so, it would be nice to contact signatories to poll them whether they signed or not (assuming signatories are real).

**Comment by cmpunches** [comment]
> If so, it would be nice to contact signatories to poll them whether they signed or not (assuming signatories are real).

@hinell  AFTER their campaign has concluded.  If you start to attack their process during it, they'll just adapt and make it harder to do that with worse long term consequences.

**Comment by cmpunches** [comment]
That said, it's still important to *track* irregularities and process changes as well as their signature counts at those points in the timeline, because that'll be the data needed when that starts to be a thing.
