### ISSUE TITLE
You are WATCHED now

### ISSUE THREAD

**Issue by hinell** [rms-support-letter/rms-support-letter.github.io#4910]
# Big Brother
Just came across a user on twitter who created a script that highlight signatories to the Support letter so that they are can be distinguished from ordinary users (prols).
This probably constitutes a GitHub's own Terms of Service violation.

Please, report the following repo (user): https://github.com/sticks-stuff/highlight-RMS-supporters

With the following message:

```
## The Issue
The reported user is an author of the repo which hosts userstyles (.css) files and JS scripts which highlight users who recently took a part in signing a letter in support of Richard M. Stallman in their expression of free will and disgust directed toward a smear campaign going on against the latter. The users who participated are highlighted in RED. The sole purpose of "extension" is to discriminate users who dared to have opinion on their own.
Link: https://github.com/sticks-stuff/highlight-RMS-supporters
Related tweet: https://twitter.com/stick_twt/status/1375993627818696704

## Terms
Github's service of terms clearly condems hosting such software:
https://docs.github.com/en/github/site-policy/github-community-guidelines#:~:text=We%20do%20not%20tolerate%20bullying,into%20bullying%20or%20harassment%20territory.

## Request
I formally ask you to conduct investigation into these matters as I strongly believe that such behavior is disruptive and creates atmosphere of intolerance and hatred.
I also ask you to take necessary steps to mitigate damage from use of this software and protect user from harassment.
```

# Screenshots
[<image src="https://user-images.githubusercontent.com/8136158/113010718-bcd7cc80-9181-11eb-8cd9-9c4e797e5579.png" width="500px"></image>](https://twitter.com/stick_twt/status/1375993627818696704)
# Related
*  #3484 (Now closed)

**Comment by BlueFlo0d** [comment]
Their code suck, just a grab from GitHub link on our main page, didn't even detected my account.
https://github.com/sticks-stuff/highlight-RMS-supporters/issues/4 XDDD

Just in case, here's my high quality (not really, one time use) code for against letter user study 
https://github.com/BlueFlo0d/fashy-detector

**Comment by BlueFlo0d** [comment]
> @BlueFlo0d Whatever. Just wanted to get you updated on these dirty stuff.
> 
> You may also want to put this buddy on your watchlist:
> [<img alt="" width="300px" src="https://user-images.githubusercontent.com/8136158/113017711-6de16580-9188-11eb-8fac-e26cedc28e62.png">](https://twitter.com/travisbrown/status/1376105308079206400)

Added adhocly as manual entry for now.
Maybe I should do some NLP stuff and spider the whole GitHub... let's save it till I got real bored.

**Comment by imachug** [comment]
We have reported them. GitHub abuse team hasn't replied yet/ignored us.
