### ISSUE TITLE
Please be kind. Remember: we are DEFENDING Free Software.

### ISSUE THREAD

**Issue by Shamar** [rms-support-letter/rms-support-letter.github.io#4931]
Friends, please, do NOT legitimate the harassers by going after their signatures.  
Grant all people the freedom we want for us (and for RMS).

First, you would legitimate the "petition letter" method, and while our letter was a needed **defence** of RMS and FSF against attackers, we should NOT legitimate these methods.

Second, you would be described as harassers, helping the attackers to pose a victims when they are not.

THIRD and more important: if any idiot that signed our letter actually goes after the signers of the other letter, we should take distance from such conduct. Victims are victims, whatever their opinion, and they deserve our support.

Remember: We are JUST defending Free Software.   
Do not, PLEASE, do not behave like the attackers, harassing single persons for their opinions.

____
NOTE Sorry @rms-support-letter, this is not an issue but I felt urged to spread this after reading #4898.

**Comment by Aspie96** [comment]
I agree.

I like this letter because I hate bullying.

They are bullies. We should not be

**Comment by cmpunches** [comment]
Agree!  If you retaliate by harassing signatories in the smear campaign, then when people look at what happened after the fact they will see both sides doing it.  You have to let it be one-sided.

**Comment by dpocock** [comment]
Taking this further, I feel it is really important to ask people why they signed the hate letter.  Many of them have had bad experiences with somebody, not necessarily Dr Stallman.  It is important to listen to their grievances and then help them find a better solution than hatred++.  The Mollies are offering them false hope and many people will either regret signing or they will realize it didn't change anything.

We are not just defending Free Software.  We are defending human rights, the presumption of innocence, the right to a fair trial and free speech.  Molly/mob rule is the road to disaster.

**Comment by cmpunches** [comment]
> Taking this further, I feel it is really important to ask people why they signed the hate letter. Many of them have had bad experiences with somebody, not necessarily Dr Stallman. It is important to listen to their grievances and then help them find a better solution than hatred++. The Mollies are offering them false hope and many people will either regret signing or they will realize it didn't change anything.
> 
> We are not just defending Free Software. We are defending human rights, the presumption of innocence, the right to a fair trial and free speech. Molly/mob rule is the road to disaster.

@dpocock Speaking of listening to their grievances, I've been trying to get hold of you to discuss a related issue to this whole thing that only you seem to be able to provide details on.  Are you at the same email address you use for the Fedora lists?

**Comment by dpocock** [comment]
Yes, please feel free to email me directly

**Comment by feverzsj** [comment]
Yeah. Although their projects already violate various civil rights laws and community rules across countries, and they really suck at coding, we can still tolerate them and help them improve their coding skill by reporting bugs to them.

**Comment by dpocock** [comment]
Apparently no woman ever made any formal complaint against RMS.  There is extensive documentation about a woman making a judicial complaint at FSFE:
http://fsfellowship.eu/matthias-kirschner-jonas-oberg-fsfe-paternity-maternity-hypocrisy/

FSFE is not FSF.  The FSFE have published many attacks on RMS, for example:
https://fsfe.org/news/2021/news-20210324-01.en.html

**Comment by Shamar** [comment]
> I feel it is really important to ask people why they signed the hate letter. [...]   
>  It is important to listen to their grievances and then help them find a better solution than hatred++.

I totally agree: talking with the people we do **not** agree, understanding their perspectives and fears, explaining (and realizing) our perspective and fears, is the fundamental building block of any community and the only real antidote/vaccine to the virus of hate and irrationality. An honest dialogue among different people is the core of democracy.

Having said that, PLEASE do not forget that most of the signers of the rms-open-letter have been mislead by false informations spread by [several news reports misrepresented Stallman’s position](https://rms-open-letter.github.io/appendix) and since the support latter has been signed by thousands people more than their own, I think they might **feel** attacked even if you approach them with the most noble intentions.

As a father of three who have faced hatred fights several times, I suggest you to do not undervalue the **feelings** of the signers. Some of them might actually **be afraid** of strangers asking something like "why did you signed an hate letter?", right now.

Exactly because we are **defending** Free Software that, being **by itself** a form of expression and Free Speech is more than just software, we must honour the freedom of speech **and the feelings** of those we do not agree with.

So my suggestion is to let the people in the lynching mob **calm down and reflect on what they did**, to not approach them on this topic if they are not close friends you know would appreciate to discuss the matter with you.

Do not forget that **most of them are in good faith**.

Do not approach them **now**. Do not approach strangers that might feel scared.  
It would NOT create any dialogue with them, it might hurt their feelings and could even be misrepresented.

There is a huge difference between writing (and signing) an open letter to **target one man** and writing (and signing) an open letter to defend him from such attack. Please, let's the difference be clear to everybody.

**Comment by hinell** [comment]
@Shamar Well considering that they either failed or didn't have enough time to see hardly will they get in touch with you on their reasoning. I think it's better to focus on debunking all the stuff RMS was said about.

**Comment by dpocock** [comment]
> > https://fsfe.org/news/2021/news-20210324-01.en.html
> 
> By this letter RMS is guilty of something nobody knows what. Seems like a European offshoot is attacking the US one.

Exactly.  The FSFE was created as a spoiler for RMS and FSFE, it is fake news as an organization.  It is funded directly by Google, Red Hat and even Microsoft:
https://fsfe.org/donate/thankgnus.en.html

You can browse a lot of articles on the Fellowship site for details
http://fsfellowship.eu/about/

There is an RSS feed too:
https://fsfellowship.eu/feed.xml

**Comment by Shamar** [comment]
> hardly will they get in touch with you on their reasoning

Well, I'm quite optimist on this, @hinell, because in fact some of them are already doing this.
Few, actually, but they **are** reflecting on what they signed.

Some even retired their signatures after realizing that they were been fooled and used.

**Comment by Pasha-From-Russia** [comment]
Stallman is a strange person, but I don't believe this "harassment hoax" around him. Like most of the recent scandals around the famous men in the US: a random woman realizes that a %some_man% touched her 20 year ago and decides to make his life hell. Bullshit. Screw RHEL, and everyone who is against RMS

**Comment by hinell** [comment]
@Shamar Lets see how everything turns out. I have seen some people taking down their signatures too already (can be seen from PRs). Not everyone, but some may eventually will come up with their regrets doing this.

**Comment by dpocock** [comment]
Many people are innocent or spur-of-the-moment participants in a mob situation.  They get caught up in the momentum.

Sometimes mob phenomena occurs by accident.  Example, the fall of the Berlin Wall involved a series of communications mishaps:
https://en.wikipedia.org/wiki/Fall_of_the_Berlin_Wall#Misinformed_public_announcements

In the attacks on Dr Stallman, some people are acting deliberately and they have been doing so for a very long time.  Debian is currently discussing a referendum to attack the FSF.  You can see the discussion is very deliberate:
https://lists.debian.org/debian-vote/2021/03/threads.html

Looking in that discussion you can see a premeditated intention of acting like a mob.  You also see high arrogance: the nastiest people in Debian feel they have the right to choose or veto the leaders of other organizations.

There are a series of emails and previous videos of Molly de Blanc showing that her orchestration of a mob is premeditated, for example:
https://www.linuxfestnorthwest.org/conferences/2019/program/proposals/305
https://archive.fosdem.org/2019/schedule/event/community_guidelines/

**Comment by Aspie96** [comment]
@Shamar 
> Few, actually, but they are reflecting on what they signed.

Any example?

(Note: I believe you, I'd just like to see examples).

**Comment by Aspie96** [comment]
I was talking about the "reflection" on what they signed.
Did you see any discussion of this?

**Comment by Shamar** [comment]
I took part to a couple of them.

But I didn't start the conversation, they did because they saw me among the signers of this letter and were **incredibly** surprised. :-)

The fact is that I'm VERY different from RMS. I criticised GNU with them several times for several architectural decisions and some of the political opinion of RMS in particular. I even thing he got some fundamentals of Free Software (slightly) wrong. And... really... they had good reasons to think I **could** have signed the rms-open-letter, since they didn't saw how sad I was when he resigned from FSF two years ago (long term friends, but far apart on the globe ;-)

So we talked about the topic a lot. We are still talking, actually... but as good friends that debate over politics.

And to be honest, they were quite shocked to see that, well... the authors of the letters they signed had to admit their faults in the appendix.

**Comment by DamieFC** [comment]
How can you criticize a group of people trying to do a good thing, how. C'mon people!

**Comment by stuardreinhild** [comment]
Wait, have you thought of it… what if *we* are the baddies? Could it be that we all are just massively mistaken. Are we the baddies?

**Comment by 6r1d** [comment]
> Wait, have you thought of it… what if we are the baddies? Could it be that we all are just massively mistaken.

First of all, open letter is just **wrong**. It accuses RMS of many things, but confirms little. We shouldn't attack a person based on that. Open-letter does nitpicking by digging through many of his conversations and putting some things out of context.

There's an article detailing why open letter is incorrect. It was often removed, but lol, not there. [Dissecting Hate Speech - The Richard M. Stallman Open Letter
](https://www.reddit.com/r/freesoftware/comments/meot29/dissecting_hate_speech_the_rms_open_letter/)

Besides that, at least some people know him think of him differently: [Richard Stallman Has Been Vilified by Those Who Don’t Know Him](https://whoisylvia.medium.com/richard-stallman-has-been-vilified-by-those-who-dont-know-him-a3907b25b4c7)

Bryan Lunduke did many videos of him and he knows Richard, as well.

We found other help with fact-checking [here](https://github.com/rms-support-letter/rms-support-letter.github.io/issues/245) and [here](https://github.com/rms-support-letter/rms-support-letter.github.io/issues/2441).

Besides that:
* https://avilarenata.medium.com/stallman-d824724b0083
* https://medium.com/@richardsmith_76348/richard-stallman-was-framed-and-misquoted-c76302bdebe

>  Are we the baddies?

No, rms-support-letter is doing good in defending and supporting a person.

**Comment by dimitris-triantafyllidis** [comment]
> Wait, have you thought of it… what if we are the baddies? Could it be that we all are just massively mistaken. Are we the baddies?

Besides the nice links by 6r1d, have you visited his personal website? There are *lots* of political notes there and also a search engine. It should be obvious that Stallman is not a misogynist, transphobic or ableist. Quite the contrary, unless one wants to attribute jokes about "EMACS virgins" to misogyny.

The kindest thing I could say about that letter and the whole campaign it is that it is sad.

**Comment by 6r1d** [comment]
> Besides the nice links by 6r1d, have you visited his personal website

Yes. It's hard to collect all the proofs in one message and I'm getting absent-minded, thank you! I mentioned that to a lot of people: you have to be very nitpicking to call Richard a negative person.

**Comment by DebianCommunity** [comment]
This is about the comment in #5614 

In the US, it is very normal for campaigns to make disclosures about the identities of their donors and the amounts of money or any other influence.
http://www.transparencypolicy.net/campaign-finance.php

There is no call to identify the children or pet photos of mob members.  But it seems prudent to identify their employers and deduce whether they signed individually or under some coercion from their management.

This thread is about DEFENDING and that is great.  To make a good defense it is imperative to know something about the attacker.  If the attacker has a military character, it would be nice to know in advance so you can be prepared.
http://debian.community/paul-tagliamonte-debian-usds-white-house-mob-ringleader/

**Comment by clort81** [comment]
> Wait, have you thought of it… what if _we_ are the baddies? Could it be that we all are just massively mistaken. Are we the baddies?

You might be.

**Comment by cmpunches** [comment]
@DebianCommunity the only shady activity I've seen is from MDB, which is well covered, but if anything is not being covered that should be, I think it is Elana Hashman and Neil McGovern's role in all of this.  This has implied OSI strategy behind it, especially given that they've publicly revealed that they had a PR team pushing this.

Elana Hashman and Neil McGovern likely set up Molly to be their patsy.  I would like to see that covered by Debian.Community.

**Comment by DebianCommunity** [comment]
Its coming

**Comment by Shamar** [comment]
@DebianCommunity to be honest I'd prefer to not be associated with things like this: http://debian.community/molly-de-blanc-arrest-and-prosecution-for-cyberbullying/

I do not believe in fighting cyber-bullies through cyber-bulling. Even if it was not your intention, publishing photos and addresses of people you do not agree with, might encourage personal attacks towards them. What they are doing, does not justify this.

So please, if you want to do a good service to our defence of FSF and RMS, remove or redact such page now.

Also, please be careful to not use this public space to distribute further aggressive or not carefully backed and double-checked contents about people signing the rms-open-letter. It would look like trying to leverage all this sad story, to spam.

**Comment by cmpunches** [comment]
I couldn't disagree more with @Shamar -- it is not cyber-bullying to call out illegal ongoing behaviour from self-proclaimed community leaders.  This was a smear campaign, and it did violate many state and federal laws, as well as the codes of conduct of every represented organization by its masterminds.

It is not "personally targeting" someone to call out an ongoing crime and offering ways to report it to authorities.  No redaction is necessary.

**Comment by DebianCommunity** [comment]
@Shamar as victims of cyberbullying, we emphasize with the victim, Dr Stallman.  This is a crime in progress.

Some years ago a schoolgirl in the UK disappeared with her teacher, they ran away to France.  Normally in abuse cases the name and photo of the child would never be published.  As she was missing, police had to publish the girl's name and photo.  This was the fastest way to stop the crime.

When the teacher was apprehended, many web sites removed the name and photo.

The bullying of Dr Stallman is a crime in progress.  We are not publishing the home address of de Blanc, we only provide the link to the closest police station because that is the most expedient way to stop the crime.

Once the police take action and Dr Stallman is safe we may remove the photo.

**Comment by Shamar** [comment]
@DebianCommunity RMS is neither under physical treat nor missing.

The person you are targetting is NOT fugitive.

What you are doing is totally unnecessary and it could perceived as an harassment.
I'd even say it could cause you legal issues in many country. And, in fact, **I would feel targetted too**.

If you want to help RMS and FSF, please STOP.

**Comment by DebianCommunity** [comment]
@Shamar the military invests billions in PsyOps research

Why?

Because it can cause harm without the "physical threat" that is blinding your judgment

**Comment by cmpunches** [comment]
As soon as their community started targeting our signatories as a result of her letter her strategy was made clear; this was a deliberate call to harassment and defamation.

He is arguably in physical danger as a result of the cyber-bullying and dog whistles to activist communities, but even if he were not, he would not need to be for it to be a crime in the united states at a federal level, or in most states (in this case mass. and NY, both of which have statutes preventing this kind of thing).

**Comment by dpocock** [comment]
There are plenty of articles / conspiracies online explaining it, scientists who use mind waves to bend spoons, etc

https://fort-russ.com/2020/09/dr-strangeloves-spoon-benders-how-the-u-s-military-learned-to-stop-worrying-and-love-the-bomb/

They don't really bend spoons.  The spoon is a metaphor for bending people's principles.

**Comment by Shamar** [comment]
I think @DebianCommunity and @cmpunches, that if you want to report a crime in your Country, you have proper instruments to do that.

This public space is not one of them.

**Comment by DebianCommunity** [comment]
the site has been updated with more Pentagon photos and links, please share it

http://debian.community/paul-tagliamonte-debian-usds-white-house-mob-ringleader/

**Comment by Aspie96** [comment]
Apparently some people on the other side are afraid of harassment.

And it's not ok.

No matter how much you disagree with them, no matter if you think they themselves are harassing it's not ok.

We do not like bullies.

Reference https://twitter.com/Aspie96/status/1380869211300499459

**Comment by Aspie96** [comment]
Lunduke spoke about how people are not signing our letter for fear of losin their job. Which is obviously wrong.

NEITHER side should be afraid. Convince with words and arguments.

**Comment by clort81** [comment]
> i do not like bullying

It's a categorical error to equate a defensive action with bullying.  It reflects an aspergic view that anything 'not nice' is equal to aggression. 

Consider the case if one person physically attacks an innocent bystander; the victim has every right to defend with any means necessary.  

Would Aspie96 cry-out 'stop bullying' to the victim there, too?

To equate legitimate defense with aggression is idiotic, infantile, lobotomized, amoral.

Furthermore, the Aspie seems unable to comprehend that those who lead and organize such attacks do so in full knowledge of the fact that they are doing wrong and are in fact the aggressor -- they just pretend they are not doing that for a public face.  There is no convincing *them* with the truth.

Those who can be reached by argument are the fence-sitters and those who value truth over conformity, but have just been misled by a false narrative.  Those can be quietly informed and convinced with the facts of the matter.

**Comment by Aspie96** [comment]
I do agree that the RMS Open Letter people are not behaving correctly of course.

But to react to that with similar behaviours would simply harm the cause.

Respond to bad behaviour with good behaviour. And when tomorrow somebody looks back they will see which side is acting which way.

We should not blur ourselves with those people we do not like

**Comment by clort81** [comment]
>But to react to that with similar behaviours would simply harm the cause.

It's possible you're right on this.  Any action needs careful consideration, especially when the enemy owns the media and can portray any defensive action as aggressive.

**Comment by Aspie96** [comment]
Act like Lunduke and speak nicely to them.

Respect them as people.

If they act viciously that will be their fault but give them the chance not to. And if they do try to help them correct this.
The purpose should not be of punishing anybody! The purpose should be to change minds with as little fights as possible.

In a phisical fight one has to defend themselves.
But to react with online bad behaviour with more online bad behaviour does not help anybody.

And if people are afraid of signing the RMS Open Letter that makes OUR letter worthless!
Because at that point the difference in the number of signatures will be explained by fear.

I don't want to say "we bullied the other side into oblivion". I do not want to say "we bullied them more than they bullied us".
A bully war is not a war I want to win.

I do want to say "despite their actions we remained successful". I do want to say "we reached a great number of people who signed our letter"

**Comment by Aspie96** [comment]
https://www.youtube.com/watch?v=BJP9o4BEziI

**Comment by clort81** [comment]
But then the actual bullies will just keep doing it.

**Comment by Aspie96** [comment]
They will keep doing it either way.

The question is if one wants to cause more damage than necessary and invalidate this letter in support for Richard Stallman or actually try and convince those who will change their mind if faced with evidence and good arguments.

Because once you have two mobs fighting each other who started it isn't that relevant. You will be in a situation in which both sides are equally irrational.

I am siding with this letter because I was convinced and I believe we should act like decent people

Those trying to shun the other side don't have my respect

**Comment by Aspie96** [comment]
I will support Richard Stallman.
I will support discussion.
I will not support revenge.

This is not a call for revenge.
This is a call for the FSF not to pick its leaders based on the actions of a mob

**Comment by clort81** [comment]
They'll have trouble doing it from prison.

**Comment by Aspie96** [comment]
As for why we must be nice to both sides
https://github.com/rms-support-letter/rms-support-letter.github.io/pull/6658#issuecomment-817926324
