### ISSUE TITLE
This badge is cool. Add to README

### ISSUE THREAD

**Issue by bnainar** [rms-support-letter/rms-support-letter.github.io#5092]
[![](https://img.shields.io/matrix/free-rms:matrix.org?logo=matrix)](https://matrix.to/#/+free-rms:matrix.org)

`[![](https://img.shields.io/matrix/free-rms:matrix.org?logo=matrix)](https://matrix.to/#/+free-rms:matrix.org)`

For Discord,
Enable widget settings ([Video tutorial](https://vimeo.com/364220040))
And add the following `![Discord](https://img.shields.io/discord/824612696150114326)` to get:

 ![Discord](https://img.shields.io/discord/824612696150114326)

**Comment by shenlebantongying** [comment]
It's useless for the purpose, and promoting none-free platform.

**Comment by nukeop** [comment]
We already have the link in the readme, the badges won't help us.
