### ISSUE TITLE
mention libreboot's statement with the letter

### ISSUE THREAD

**Issue by Kreyren** [rms-support-letter/rms-support-letter.github.io#5174]
See https://libreboot.org/news/rms.html

**Comment by nukeop** [comment]
We are not affiliated. This is a separate piece.

**Comment by Kreyren** [comment]
> We are not affiliated. This is a separate piece.

True, but i believe it to be beneficial to show that foundations/corporations has same/similar views.

Doesn't mean that it has to be affiliated with this letter.

Note the other letter providing `statements.md` this way.

**Comment by nukeop** [comment]
Libreboot is literally one person now. There have been many articles supporting Stallman already, and I don't want to dilute our message by flooding people reading it with a lot of links and additional materials.

**Comment by Kreyren** [comment]
fair point
