### ISSUE TITLE
We need to work out conter-strategy.

### ISSUE THREAD

**Issue by AdUser** [rms-support-letter/rms-support-letter.github.io#5185]
With only-defence you can't win the war even in theory. These shit-eaters already making an execution lists:

https://github.com/sticks-stuff/highlight-RMS-supporters
https://github.com/aaronbassett/rms-letter-sigs

...and sending threats by email to known signers:

https://github.com/rms-support-letter/rms-support-letter.github.io/issues/3484

...and not are going to stop. So, why we should be tolerate?

At least we can report an abuse on users, involved in such activity (but not all signers of "open-letter") and repo with original letter. It's completely legal: all of these users/repo violates github community rules (defamation/harassment) and at least EU GDPR. If they don't want to talk[1] and discuss, we have no other options. After few hundreds of abuses on these repo/authors even github will have to react.

Next. We can initiate our own movement to seek resignation of known RMS "haters", such as Neil McGovern. His behaviour unethical and violates the same rules named above. I think this is incompatible with any manager position in any FOSS-related organization.

We are now fighting not only for RMS, we are fighting for right to call spade a spade.

[1] See https://github.com/rms-support-letter/rms-support-letter.github.io/issues/175

**Comment by hinell** [comment]
1. These execution lists pretty nicely characterize those who created & use them. They are pathetic miserable creatures who CAN'T tolerate others' opinions while WE - can do it easily. Freedom of Speech should prevail.
2. The email profile was proven to be a fake one. It was created and immediately deleted (see [this reply][post]). No side so far has admitted they used intimidation tactic. So this doesn't warrant any counter measures unless situation repeats and there would be more evidence.

[post]: https://github.com/rms-support-letter/rms-support-letter.github.io/issues/3484#issuecomment-808923186

**Comment by Aspie96** [comment]
What we really need as a counterstrategy is *join the FSF* or donate to it.

And in the message, support RMS.

We want to show that with RMS the FSF gets more support, not less

**Comment by realGWM** [comment]
> shit-eaters
Just my 5 cents, but I think that saying things like that doesn't make our movement look good. :man_shrugging:
