### ISSUE TITLE
Remove index.md from repo

### ISSUE THREAD

**Issue by imachug** [rms-support-letter/rms-support-letter.github.io#530]
Remove it from repo to prevent people from creating PRs on it, and generate it at build phase via GitHub Action.

Will implement in a few hours if no one does that before.

**Comment by nukeop** [comment]
I will remove it once I merge all the PRs that add signatures in index.md, then convert them to the new format.

**Comment by pizdjuk** [comment]
I think it was a difficult, but yet simple way (comparing to creating a fork) to add the signature....

**Comment by tdemin** [comment]
@nukeop I know it's a by-hand effort and all, but these kind of letters have the resonance if updated timely.

**Comment by nukeop** [comment]
I'm doing it as fast as I can. I looked into ways of bulk-merging PRs but they still need to be reviewed manually to make sure no malicious entries are added.

**Comment by nukeop** [comment]
https://github.com/rms-support-letter/rms-support-letter.github.io/pull/875

example why I still need to review everything manually

**Comment by imachug** [comment]
@nukeop Is it just me or rms-support-letter.github.io doesn't seem to be updated often? There are way less entries than merged PRs there.

**Comment by Jan200101** [comment]
PR merging seems to be automated hence why the index.md was replaced with a scalable alternative

```
Pull requests merged within 12 hours - due to a huge volume of PRs they will be merged in batches
```

**Comment by RealJTG** [comment]
> I'm doing it as fast as I can. I looked into ways of bulk-merging PRs but they still need to be reviewed manually to make sure no malicious entries are added.

Thanks for your work, @nukeop! Any ways we can help you? Mb we can help to put labels on PRs or something else?

**Comment by imachug** [comment]
Done
