### ISSUE TITLE
Change the flag of Taiwan to the correct one.

### ISSUE THREAD

**Issue by rldmt** [rms-support-letter/rms-support-letter.github.io#5359]
I noticed in the README.md file that the flag of Taiwan is the same as China. Last time I checked Taiwan is a separate country :taiwan: . Anyway you decide. I am not even chinese :smile:

**Comment by shenlebantongying** [comment]
fixed https://github.com/rms-support-letter/rms-support-letter.github.io/commit/782115f28f81bf2f5d450afc8bd4e991d04319d9
