### ISSUE TITLE
The link to the video on README is broken

### ISSUE THREAD

**Issue by taiju** [rms-support-letter/rms-support-letter.github.io#5407]
The URL is below.
https://invidious.snopyta.org/watch?v=1lz5S5oS8CU

**Comment by shenlebantongying** [comment]
Not broken for me.

![image](https://user-images.githubusercontent.com/20123683/113236880-c5103480-9273-11eb-887e-caa6efda7c43.png)

**Comment by shenlebantongying** [comment]
https://invidious.snopyta.org/watch?v=1lz5S5oS8CU

**Comment by taiju** [comment]
I just clicked on it and it was working.
It may have been a timing issue.
