### ISSUE TITLE
Page update

### ISSUE THREAD

**Issue by pcav** [rms-support-letter/rms-support-letter.github.io#5478]
Hi, I have submitted a PR, which has been merged. When is the page https://rms-support-letter.github.io/ updated? I still don't see my support. Thanks.

**Comment by shenlebantongying** [comment]
Already updated :)

![image](https://user-images.githubusercontent.com/20123683/113282563-1c82c480-92b5-11eb-8b3a-4c3ba99ce03a.png)

**Comment by pcav** [comment]
Thanks @shenlebantongying
