### ISSUE TITLE
Watch out on Freenode and OFTC

### ISSUE THREAD

**Issue by cmpunches** [rms-support-letter/rms-support-letter.github.io#5551]
They have some folks in the corporate camp.  I walked into a kline on OFTC and FreeNode last night after being asked about the RMS support letter by Tom Wesley on the OFTC board.

If people know you, might be a good idea to stay low for a few weeks on both networks, and watch out for bully staffers.  In my case I can just fart a proxy when I need to so it doesn't really have much impact but if you have alot of investment in your nick you might want to be aware.

**Comment by 6r1d** [comment]
Thank you, I will be careful.

**Comment by dpocock** [comment]
We need to develop alternatives to these platforms.  This has always been a big part of my work.

This situation is a great opportunity to reflect on the question: what would be the right alternative to IRC?

**Comment by cmpunches** [comment]
@dpocock Why, another IRC network, of course!

**Comment by nukeop** [comment]
I don't get it, what are you implying is going to happen, and why?
