### ISSUE TITLE
Add support for multiple website addresses.

### ISSUE THREAD

**Issue by yuvallangerontheroad** [rms-support-letter/rms-support-letter.github.io#5575]
Something like:

```
name: Yuval Langer
link: https://github.com/yuvallanger/
link: https://gitlab.com/yuvallanger/
```

Thank you either way.

**Comment by shenlebantongying** [comment]
Unless you make a PR, no change will be made.

**Comment by 6r1d** [comment]
It is an interesting idea, and I think it would be helpful to add this. Personally, I don't know the list generator that well to extend it safely.

**Comment by teunissenstefan** [comment]
How would you try to display this? Something like the following?
[Yuval Langer](https://github.com/yuvallanger/) [Website 2](https://github.com/yuvallanger/) [Website 3](https://github.com/yuvallanger/)
I have a feeling that this is easy to implement but unnecessary for something like this letter.

**Comment by Bluesboy** [comment]
> ```
> name: Yuval Langer
> link: https://github.com/yuvallanger/
> link: https://gitlab.com/yuvallanger/
> ```

In YAML it would be like:

```
name: My Name
link:
  - https://site.one
  - https://site.two
```
But as @teunissenstefan pointed it's unnecessary.

**Comment by nukeop** [comment]
I'm opposed to this for two reasons:
- The name already server as the text of the link, and I don't see where the other link would go
- We're slowly reaching the max number of signatories we can achieve, so almost no one would be able to use this new format

**Comment by jobbautista9** [comment]
Btw, a possible workaround for this, if you want to link to multiple websites, is to create a webpage of your own linking to those other sites, and using that page as your link for the signature.
