### ISSUE TITLE
getting support from Vietnam, Nicaragua and Afghanistan

### ISSUE THREAD

**Issue by DebianCommunity** [rms-support-letter/rms-support-letter.github.io#5680]
The comments earlier today suggest that the attacks on RMS have Pentagon connections.  Maybe it is just a conspiracy theory.
https://github.com/rms-support-letter/rms-support-letter.github.io/issues/4931#issuecomment-812612336

There are only three countries where the US military has not prevailed: Vietnam, Nicaragua and Afghanistan

We had DebConf12 in Nicaragua and they showed us all the weapons they seized from the US military.  They keep them in a museum.  Various sites are keeping leaks from Debian-Private in a museum, did anybody check for hints about the people who want to hurt Dr Stallman?
https://debian.community/debian-private-leaked/

Can we ask the officials of Vietnam, Nicaragua and Afghanistan to sign the RMS Support Letter?

**Comment by 6r1d** [comment]
> Maybe it is just a conspiracy theory

And it's possible. Can we just ask the officials of three countries telling them "hey, we have a theory, **and it may be a conspiracy theory**, but please sign here"? Wouldn't that discredit us? And more importantly, shouldn't the free software be independent from politics?

**Comment by nukeop** [comment]
Please don't spread this timecube stuff here.
