### ISSUE TITLE
Neil McGovern is continuing to modify the smear letter package

### ISSUE THREAD

**Issue by cmpunches** [rms-support-letter/rms-support-letter.github.io#5854]
Apologies if this is not the right place, but, as is well known, the open letter is preventing people who disagree with the ethical nature of their strategies from reporting issues on their repository:

https://github.com/rms-open-letter/rms-open-letter.github.io/commit/6a2618b1b7c2934ddb9c9ca4e4bf845dca61e54b

**Comment by shenlebantongying** [comment]
"their own"?

I don't like it.

Project leaders like fedora's and KDE's don't agree all the accusations and the tone of the letter, so they publish their own. They are gentlemen who at least would give RMS some dignity. Fedora's one doesn't mention RMS at all.

It doesn't mean their statements are part of the unholy open letter which violate various CoC.

![image](https://user-images.githubusercontent.com/20123683/113488968-5e676280-948f-11eb-9c72-0465c957a00e.png)

**Comment by cmpunches** [comment]
> "their own"?
> 
> I don't like it.
> 
> Project leaders like fedora's and KDE's don't agree all the accusations and the tone of the letter, so they publish their own. They are gentlemen who at least would give RMS some dignity. Fedora's one doesn't mention RMS at all.
> 
> It doesn't mean their statements are part of the unholy open letter which violate various CoC.
> 
> ![image](https://user-images.githubusercontent.com/20123683/113488968-5e676280-948f-11eb-9c72-0465c957a00e.png)

It is a transparently manipulative effort I see there, where they have failed to garner community support and believe they can rest their laurels on "organizations in agreement" by tying them in after the fact to try to reverse the perception created by their resounding defeat in this PR campaign.

This also brings some light to their strategy:  It is not about RMS -- it is about the destruction of the FSF so that corporates can come in and wreck the place and steal all the treasure.

**Comment by appetrosyan** [comment]
@shenlebantongying I can understand KDE being gentlemanly, but Fedora?

**Comment by dimitris-triantafyllidis** [comment]
Saw this on Twitter a few moments ago, FWIW.

![Screenshot from 2021-04-05 22-36-18](https://user-images.githubusercontent.com/39795232/113617802-7ab9f980-965f-11eb-9b17-991ecb3d6369.png)
