### ISSUE TITLE
Add contact details for non-English speakers

### ISSUE THREAD

**Issue by dimqua** [rms-support-letter/rms-support-letter.github.io#6309]
Probably it would be beneficial to add regional contact e-mail address(es) for individuals and people who represent various non-English media, so they could contact us using their native language. What do you think?

**Comment by 6r1d** [comment]
I believe it is useful for a short-term scenario. At some point, we'll have to stop accepting votes, but wider press reaction is nevertheless important.

**Comment by shenlebantongying** [comment]
I am not a pro-American/western, but English seems to be an in-fact international language. Besides, we (the strawmen of this repo) only understand 3 languages.............

**Comment by 6r1d** [comment]
> but English seems to be an in-fact international language today.

Yeah, and he's interested in an email for Russian press now.

**Comment by nukeop** [comment]
We will only accept contact emails in English, supporting more would be too costly.
