### ISSUE TITLE
spam emails associated with signing the support letter

### ISSUE THREAD

**Issue by theoden8** [rms-support-letter/rms-support-letter.github.io#6586]
I'm getting spammed with some shit polls that i don't bother reading with regards to signing the support letter..

I'm dealing with exam situation and this is annoying, what are the options.

reported as spam/phishing.

**Comment by shenlebantongying** [comment]
https://github.com/rms-support-letter/rms-support-letter.github.io/issues/6450

Ignore it.

**Comment by 6r1d** [comment]
Was it some CIVS poll? It has an "unsubscribe" link: https://civs1.civs.us/cgi-bin/mail_mgmt.pl if so

**Comment by jobbautista9** [comment]
Closing as duplicate of #6450
