### ISSUE TITLE
Подскажите,  почему отклонили мой голос: "Your link doesn't work and your account is too new." ?

### ISSUE THREAD

**Issue by jemiapo** [rms-support-letter/rms-support-letter.github.io#6618]
Замержил yaml- все по образу  и подобию c указаниями:
1. дал фио
2. дал ссылку на гугл плей (тк прилож своего сайта не имеет - проект еще совсем сырой)
https://play.google.com/store/apps/details?id=io.pokerplatform

Мне пришел отказ принять мой голос с  формулировкой "Your link doesn't work and your account is too new."
3. ссылка вроде у мну открывается в РФ
4. мой акк  на гите зареган  с February 17, 2021 - скоро будет месяц как.
Ну и что?
Где и в каких правилах голосования есть ограничания по "account is too new" ?
Спасибо заранее за конструктивный ответ.

**Comment by jemiapo** [comment]
Все меня замержили!
Братья я с вами !
Ишью можно закрывать.
![image](https://user-images.githubusercontent.com/79193890/114275071-d30b4580-9a29-11eb-8705-f7cd64677ba8.png)

**Comment by 6r1d** [comment]
Привет. Я как раз занимаюсь подтверждениями, поэтому думаю, что мне хватает понимания ответить.
...
Но пока я писал ответ, страница обновилась. Привет, ура!
