### ISSUE TITLE
Link to  revoke-open-letter-signature

### ISSUE THREAD

**Issue by Aspie96** [rms-support-letter/rms-support-letter.github.io#6686]
There should be a link to the revoke-open-letter-singature repo

**Comment by nukeop** [comment]
I was asked for the letter to not be linked to supporting RMS in any way, sorry. It's better if it stays neutral.

**Comment by Aspie96** [comment]
But I am not asking for the remove letter to link to the support letter.
Rather for the support letter to link to the remove letter, so that those who signed the support letter after signing the open letter know how to remove their signature.

I don't see how it coult be a problem. What am I missing?
