### ISSUE TITLE
Is this safe to sign?

### ISSUE THREAD

**Issue by nagatsu-chan** [rms-support-letter/rms-support-letter.github.io#6742]
Hi, 

I am wondering if this is safe to sign while circumcised. 

Thank you.

**Comment by shenlebantongying** [comment]
Hahahaha. Yes, go sign please.

https://github.com/sticks-stuff/highlight-RMS-supporters/pull/56

**Comment by nagatsu-chan** [comment]
> Hahahaha. Yes, totally safe. Go sign please.
> 
> Welcome to the family of getting highlighted, BTW. You will be interested in knowing or working with 6k fellow signatories :)
> 
> [sticks-stuff/highlight-RMS-supporters#56](https://github.com/sticks-stuff/highlight-RMS-supporters/pull/56)

Are you sure? I do not see any statements on the README that would suggest this is safe for people who are circumcised.

**Comment by shenlebantongying** [comment]
I am very sad to inform you that your d*ck blocks your blood circulation system.
