### ISSUE TITLE
Are signers of this proposal being blacklisted?

### ISSUE THREAD

**Issue by steveeq1** [rms-support-letter/rms-support-letter.github.io#6746]
I read somewhere on reddit that signers of this petition are being blacklisted by companies? Is this true? 

I'm not ashamed of my position and stand by it, but I find it interesting that people would go that out of their way to do something like that over something so petty.

**Comment by 6r1d** [comment]
https://github.com/rms-support-letter/rms-support-letter.github.io/discussions/6749
