### ISSUE TITLE
I have a picture of RMS and GNU / Linux persecuted.

### ISSUE THREAD

**Issue by zhenruyan** [rms-support-letter/rms-support-letter.github.io#6838]
![b4a400c1ab842b06ea593ff0df48aca](https://user-images.githubusercontent.com/9253251/115202377-eb194e00-a128-11eb-86f7-fbe6b2391103.jpg)

**Comment by zhenruyan** [comment]
Hope to play a role in the activity

**Comment by 6r1d** [comment]
Spooky!
