### ISSUE TITLE
Sipmlify signing for those, who cant into IT

### ISSUE THREAD

**Issue by pizdjuk** [rms-support-letter/rms-support-letter.github.io#810]
I know, that there exists a Mail info@fsf.org etc., but to show that the community behind RMS are big it is important to accumulate the signing here. And this is done, if normal users (not IT-guys) could sign too. Actual signing process is nearly impossible to understand. So, please, make some mail-adress from where someone will pick the signings and add them to the list

**Comment by Watcher3056** [comment]
Yeah, there is a lot of requests about it, outside of github

**Comment by nukeop** [comment]
Make a comment in #837 if you want to be added without making a pull request.
