### ISSUE TITLE
[Feature Request] Numbered list of signatures?

### ISSUE THREAD

**Issue by d-sfounis** [rms-support-letter/rms-support-letter.github.io#831]
Hey, would you consider having the list of signees be **numbered**?

Just for the added ease of being able to read the number of signatures quickly.

**Comment by cl0ne** [comment]
BTW rms-open-letter.github.io has that

**Comment by cmd410** [comment]
It will be done as soon as all PRs that modify `index.md` and #718 will be merged.

**Comment by imachug** [comment]
Done
