### ISSUE TITLE
Accept patches through public mailing list

### ISSUE THREAD

**Issue by a1batross** [rms-support-letter/rms-support-letter.github.io#843]
GitHub is non-free platform and many people who really support free software, just refuse to use it.

I suggest making a mailing list for those people.

**Comment by appetrosyan** [comment]
And post it to #837

**Comment by psymin** [comment]
Perhaps this should be hosted somewhere other than Github?

**Comment by a1batross** [comment]
@psymin hosting doesn't make any difference, git is decentralized. For example, I can easily mirror it to my own Gitea instance.

The problem is contributing. Many, many people don't accept Microsoft GitHub.

**Comment by nukeop** [comment]
I'm talking to people from SpywareWatchdog, someone over there is willing to set up a working email address for signatures.

**Comment by AlexVRud** [comment]
We need an email where patches will be sent and people who will sign these patches.

**Comment by brown121407** [comment]
@nukeop, we can set up a Sourcehut repo and a mailing list over there with very little effort (two clicks). That would make it very easy to accept patches and even just plain requests by people who don't know how to send patches. Let us know if you think it's a good idea and agree to link it to this repo, because there's no reason to become fragmented. I volunteer to manage it, apply patches and all that, if you need someone.

**Comment by gorshunovr** [comment]
Emails in support of RMS would need to be added to this repo into a subdirectory as files for traceability. Would you do that, @brown121407 ?

**Comment by brown121407** [comment]
@gorshunovr, like saving the actual message file in a folder specifically made to store the mails themselves, besides the one with the signatures? Wouldn't having a public mailing list suffice?

**Comment by gorshunovr** [comment]
@brown121407 _public_ mailing list would suffice.

**Comment by Tyil** [comment]
I think this can be closed now that ~tyil/rms-support@lists.sr.ht has been added to the page. Archives can be found at https://lists.sr.ht/~tyil/rms-support, for those who're interested.
