### ISSUE TITLE
[Feature request] Sort and add new names alphabetically?

### ISSUE THREAD

**Issue by andrew-phi** [rms-support-letter/rms-support-letter.github.io#89]
Just for ease of reading.

**Comment by AnimusPEXUS** [comment]
I disagree: in case of such sorting, it will be harder to track down malicious commits, if any.
just write some python/node script for your self

**Comment by imachug** [comment]
What about a github action that just checks if the list is sorted?

**Comment by andrew-phi** [comment]
AnimusPEXUS: how so? And what are malicions commits? Removal of signatures?

**Comment by appetrosyan** [comment]
I propose sorting the names alphabetically only after a set threshold is surpassed.

**Comment by AnimusPEXUS** [comment]
> how so? And what are malicions commits? Removal of signatures?

removal, duplicates, vandalism

**Comment by nukeop** [comment]
Implemented
