### ISSUE TITLE
Click Like on this to avoid filling name/link or creation of PR!

### ISSUE THREAD

**Issue by hardhub** [rms-support-letter/rms-support-letter.github.io#994]
If you like something on github then others can see that and open your profile.  
Any who wants to be public can provide his/her email in account settings (as well as url and so on).

And all others who just want to show their position and **support Richard Matthew Stallman** just LIKE THIS POST ))

P.S. To click star on this repo is also good idea.

**Comment by vizart** [comment]
Stallman is the Man! No.Its a MAN!!!

**Comment by CarlosGS** [comment]
No, people should either submit a pull request or comment here: https://github.com/rms-support-letter/rms-support-letter.github.io/issues/837
It's signatures that count.

**Comment by hardhub** [comment]
> 
> 
> No, people should either submit a pull request or comment here: #837
> It's signatures that count.

To be published of course Carlos! ))

**Comment by TNTBOMBOM** [comment]
better to close or remove this ticket since it doesnt count for the likes, as some might like the article and leave without reading thinking they did sign to support rms by doing that (specially the title is misleading). 

cc @nukeop

**Comment by imachug** [comment]
Agreed. One more question then -- should we convert the upvotes on this issue to real signatures?

**Comment by TNTBOMBOM** [comment]
If you can do it, I have no idea how to do that tbh.


> Agreed. One more question then -- should we convert the upvotes on this issue to real signatures?
>

**Comment by imachug** [comment]
The question is not about whether I can do it, it's whether that would be fair and legal.

**Comment by TNTBOMBOM** [comment]
I think so, since they liked the article which support RMS but make sure 
they are not as well subscribed using another channel 
(github,email,..etc) to avoid duplication.


> The question is not about whether I can do it, it's whether that would be fair and legal.
>
